import { formatStory } from "./formatter";
import type { SourceRange, StoryDocument, StorySyntaxNode } from "./model";
import { parseStory } from "./parser";
import { parseTypedExpression, type ExpressionValueType } from "./expression";

export type StorySymbolKind="label"|"variable"|"character"|"asset";
export interface StoryLanguageContext {readonly variables:readonly {readonly id:string;readonly type:Exclude<ExpressionValueType,"unknown">}[];readonly characters:readonly string[];readonly assets:readonly string[];}
export interface StorySymbolDefinition {readonly kind:StorySymbolKind;readonly name:string;readonly source:"script"|"project";readonly range?:SourceRange;}
export interface StorySymbolReference {readonly kind:StorySymbolKind;readonly name:string;readonly role:"read"|"write"|"target";readonly range:SourceRange;readonly nodeKind:StorySyntaxNode["kind"];}
export interface StoryLanguageDiagnostic {readonly code:"DUPLICATE_LABEL"|"UNKNOWN_LABEL"|"UNKNOWN_VARIABLE"|"UNKNOWN_CHARACTER"|"UNKNOWN_ASSET"|"INVALID_EXPRESSION"|"TYPE_MISMATCH";readonly message:string;readonly range:SourceRange;}
export interface StoryLanguageIndex {readonly definitions:readonly StorySymbolDefinition[];readonly references:readonly StorySymbolReference[];readonly diagnostics:readonly StoryLanguageDiagnostic[];}
export interface StoryCompletion {readonly kind:"keyword"|StorySymbolKind;readonly label:string;readonly insertText:string;}
const args=(raw:string)=>Object.fromEntries([...raw.matchAll(/(?:^|\s)([A-Za-z_][A-Za-z0-9_-]*)=([^\s]+)/g)].map((match)=>[match[1]!,match[2]!]));
const replaceWord=(source:string,oldName:string,newName:string)=>source.replace(new RegExp(`(?<![A-Za-z0-9_])${oldName.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}(?![A-Za-z0-9_])`,"g"),newName);
export function buildStoryLanguageIndex(storyDocument:StoryDocument,context:StoryLanguageContext):StoryLanguageIndex{const definitions:StorySymbolDefinition[]=[...context.variables.map((item)=>({kind:"variable" as const,name:item.id,source:"project" as const})),...context.characters.map((name)=>({kind:"character" as const,name,source:"project" as const})),...context.assets.map((name)=>({kind:"asset" as const,name,source:"project" as const}))],references:StorySymbolReference[]=[];const diagnostics:StoryLanguageDiagnostic[]=[];const labels=new Map<string,SourceRange>(),variableTypes=Object.fromEntries(context.variables.map((item)=>[item.id,item.type]));const add=(kind:StorySymbolKind,name:string,role:StorySymbolReference["role"],node:StorySyntaxNode)=>references.push({kind,name,role,range:node.range,nodeKind:node.kind});for(const node of storyDocument.nodes){if(node.kind==="label"){const previous=labels.get(node.name);if(previous)diagnostics.push({code:"DUPLICATE_LABEL",message:`Duplicate label: ${node.name}`,range:node.range});else {labels.set(node.name,node.range);definitions.push({kind:"label",name:node.name,source:"script",range:node.range});}}else if(node.kind==="choice-option"||node.kind==="jump"||node.kind==="call"||node.kind==="condition")add("label",node.targetLabel,"target",node);if(node.kind==="dialogue")add("character",node.speakerId,"read",node);if(node.kind==="directive"){const parameters=args(node.argumentsRaw);for(const key of ["asset","transitionAsset"]){const value=parameters[key];if(value)add("asset",value,"read",node);}}if(node.kind==="set"){add("variable",node.variable,"write",node);const expression=parseTypedExpression(node.expressionRaw,variableTypes);expression.identifiers.forEach((item)=>add("variable",item.name,"read",node));expression.issues.forEach((issue)=>diagnostics.push({code:issue.code==="TYPE_MISMATCH"?"TYPE_MISMATCH":issue.code==="UNKNOWN_VARIABLE"?"UNKNOWN_VARIABLE":"INVALID_EXPRESSION",message:issue.message,range:node.range}));const target=variableTypes[node.variable];if(target&&expression.valueType!=="unknown"&&target!==expression.valueType)diagnostics.push({code:"TYPE_MISMATCH",message:`Cannot assign ${expression.valueType} to ${node.variable}:${target}`,range:node.range});}if(node.kind==="condition"){const expression=parseTypedExpression(node.expressionRaw,variableTypes);expression.identifiers.forEach((item)=>add("variable",item.name,"read",node));expression.issues.forEach((issue)=>diagnostics.push({code:issue.code==="TYPE_MISMATCH"?"TYPE_MISMATCH":issue.code==="UNKNOWN_VARIABLE"?"UNKNOWN_VARIABLE":"INVALID_EXPRESSION",message:issue.message,range:node.range}));if(expression.valueType!=="unknown"&&expression.valueType!=="boolean")diagnostics.push({code:"TYPE_MISMATCH",message:"Condition expression must be boolean",range:node.range});}}
  const known={label:new Set(labels.keys()),variable:new Set(context.variables.map((item)=>item.id)),character:new Set(context.characters),asset:new Set(context.assets)};for(const reference of references)if(!known[reference.kind].has(reference.name))diagnostics.push({code:reference.kind==="label"?"UNKNOWN_LABEL":reference.kind==="variable"?"UNKNOWN_VARIABLE":reference.kind==="character"?"UNKNOWN_CHARACTER":"UNKNOWN_ASSET",message:`Unknown ${reference.kind}: ${reference.name}`,range:reference.range});return {definitions,references,diagnostics};}
export function storyCompletions(context:StoryLanguageContext,prefix=""):readonly StoryCompletion[]{const needle=prefix.toLowerCase();const values:StoryCompletion[]=[...['scene','narrate','choice','label','jump','call','return','set','if','wait','end','@background','@show','@audio'].map((label)=>({kind:"keyword" as const,label,insertText:label})),...context.variables.map((item)=>({kind:"variable" as const,label:item.id,insertText:item.id})),...context.characters.map((label)=>({kind:"character" as const,label,insertText:label})),...context.assets.map((label)=>({kind:"asset" as const,label,insertText:label}))];return values.filter((item)=>item.label.toLowerCase().includes(needle));}
export function findStoryDefinition(index:StoryLanguageIndex,kind:StorySymbolKind,name:string):StorySymbolDefinition|undefined{return index.definitions.find((item)=>item.kind===kind&&item.name===name);}
export function findStoryReferences(index:StoryLanguageIndex,kind:StorySymbolKind,name:string):readonly StorySymbolReference[]{return index.references.filter((item)=>item.kind===kind&&item.name===name);}
export function renameStorySymbol(source:string,kind:StorySymbolKind,oldName:string,newName:string):{readonly source:string;readonly storyDocument:StoryDocument}{if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(newName))throw new Error("Replacement symbol is invalid");const storyDocument=parseStory(source);if(storyDocument.diagnostics.some((item)=>item.severity==="error"))throw new Error("Cannot refactor a story with syntax errors");const nodes=storyDocument.nodes.map((node):StorySyntaxNode=>{if(kind==="label"){if(node.kind==="label"&&node.name===oldName)return {...node,name:newName};if((node.kind==="choice-option"||node.kind==="jump"||node.kind==="call"||node.kind==="condition")&&node.targetLabel===oldName)return {...node,targetLabel:newName};}if(kind==="variable"){if(node.kind==="set")return {...node,variable:node.variable===oldName?newName:node.variable,expressionRaw:replaceWord(node.expressionRaw,oldName,newName)};if(node.kind==="condition")return {...node,expressionRaw:replaceWord(node.expressionRaw,oldName,newName)};}if(kind==="character"&&node.kind==="dialogue"&&node.speakerId===oldName)return {...node,speakerId:newName};if(kind==="asset"&&node.kind==="directive")return {...node,argumentsRaw:node.argumentsRaw.replace(/((?:^|\s)(?:asset|transitionAsset)=)([^\s]+)/g,(_,prefix:string,value:string)=>`${prefix}${value===oldName?newName:value}`)};return node;});const next={...storyDocument,nodes};const formatted=formatStory(next);return {source:formatted,storyDocument:parseStory(formatted)};}
