import { describe,expect,it } from "vitest";
import { buildStoryLanguageIndex, createIncrementalStoryState, deleteP0Node, findStoryDefinition, findStoryReferences, formatStory, insertP0Node, insertP0NodeBefore, moveP0Node, moveP0NodeBefore, parseStory, parseTypedExpression, renameStorySymbol, semanticSnapshot, storyCompletions, storyDocumentHash, updateIncrementalStoryLine, updateP0Node } from "./index";
const source=`scene "分支测试" @id(scene_branch) @plugin(valid=true)
# 注释与 Ruby：｜放送室《ほうそうしつ》
narrate "广播站仍然亮着。" @sid(statement_narration) @id(text_narration) @ruby(enabled)
label start @id(statement_label_start)
set trust = trust + 1 @id(statement_set)
if trust >= 2 && has_key -> unlocked @id(statement_condition)
choice "选择路线" @id(statement_choice)
  "进入" -> unlocked @id(option_enter)
  "离开" -> ending @id(option_leave)
label unlocked @id(statement_label_unlocked)
@background asset=background_room transition=fade custom=preserved @id(statement_background)
@show asset=character_aya slot=main expression=smile @id(statement_show)
@audio asset=bgm_theme bus=bgm loop=true @id(statement_audio)
call interlude @id(statement_call)
jump ending @id(statement_jump)
label interlude @id(statement_label_interlude)
wait 250ms @id(statement_wait)
checkpoint @id(statement_checkpoint)
return @id(statement_return)
label ending @id(statement_label_ending)
end "完成" @id(statement_end)
@future-plugin payload={opaque:true}
`;
const context={variables:[{id:"trust",type:"number" as const},{id:"has_key",type:"boolean" as const}],characters:["character_aya"],assets:["background_room","character_aya","bgm_theme"]};
describe("N20 Story Language P0",()=>{
  it("parses every P0 node and preserves comments, unknown commands, CJK/Ruby, IDs, and unknown valid parameters",()=>{const document=parseStory(source);expect(document.diagnostics.filter((item)=>item.severity==="error")).toEqual([]);expect(document.nodes.map((item)=>item.kind)).toEqual(expect.arrayContaining(["narration","choice","label","jump","call","return","set","condition","wait","checkpoint","end","directive","opaque","comment"]));const formatted=formatStory(document);expect(formatted).toContain("checkpoint @id(statement_checkpoint)");expect(formatted).toContain("｜放送室《ほうそうしつ》");expect(formatted).toContain("custom=preserved");expect(formatted).toContain("@future-plugin payload={opaque:true}");expect(semanticSnapshot(parseStory(formatted))).toEqual(semanticSnapshot(document));});
  it("requires checkpoint to carry exactly one stable source identity",()=>{expect(parseStory(`scene "Checkpoint" @id(scene_checkpoint)\ncheckpoint\n`).diagnostics).toContainEqual(expect.objectContaining({code:"MALFORMED_CHECKPOINT"}));expect(parseStory(`scene "Checkpoint" @id(scene_checkpoint)\ncheckpoint @id(checkpoint_one) extra\n`).diagnostics).toContainEqual(expect.objectContaining({code:"MALFORMED_CHECKPOINT"}));});
  it("uses a typed expression grammar and rejects JavaScript syntax",()=>{expect(parseTypedExpression("trust + 1 >= 2 && has_key",{trust:"number",has_key:"boolean"})).toMatchObject({valueType:"boolean",issues:[]});expect(parseTypedExpression("1-2",{})).toMatchObject({valueType:"number",issues:[]});expect(parseTypedExpression("globalThis.process.exit()",{}).issues.map((item)=>item.code)).toContain("UNEXPECTED_TOKEN");expect(parseTypedExpression("trust + has_key",{trust:"number",has_key:"boolean"}).issues.map((item)=>item.code)).toContain("TYPE_MISMATCH");});
  it("supports nested conditions and reports unresolved project/script references",()=>{expect(parseTypedExpression("(trust >= 2 && has_key) || (trust == 9)",{trust:"number",has_key:"boolean"})).toMatchObject({valueType:"boolean",issues:[]});const broken=parseStory(`scene "Broken" @id(scene_broken)\nmissing: Hi @sid(statement_line) @id(text_line)\nif unknown_flag -> nowhere @id(statement_if)\n`),index=buildStoryLanguageIndex(broken,context);expect(index.diagnostics.map((item)=>item.code)).toEqual(expect.arrayContaining(["UNKNOWN_CHARACTER","UNKNOWN_VARIABLE","UNKNOWN_LABEL"]));});
  it("builds diagnostics, completion, definition, and reference indexes",()=>{const index=buildStoryLanguageIndex(parseStory(source),context);expect(index.diagnostics).toEqual([]);expect(storyCompletions(context,"trust")).toContainEqual(expect.objectContaining({kind:"variable",label:"trust"}));expect(findStoryDefinition(index,"label","ending")).toMatchObject({source:"script"});expect(findStoryReferences(index,"label","ending")).toHaveLength(2);expect(findStoryReferences(index,"variable","trust").map((item)=>item.role)).toEqual(["write","read","read"]);});
  it("renames labels, variables, characters, and assets without changing stable IDs",()=>{let current=source;for(const [kind,from,to] of [["label","ending","finale"],["variable","trust","affinity"],["asset","bgm_theme","bgm_night"]] as const)current=renameStorySymbol(current,kind,from,to).source;const document=parseStory(current);expect(document.diagnostics.filter((item)=>item.severity==="error")).toEqual([]);expect(current).toContain("jump finale @id(statement_jump)");expect(current).toContain("set affinity = affinity + 1 @id(statement_set)");expect(current).toContain("asset=bgm_night");expect(current).toContain("@id(statement_end)");});
  it("inserts, updates, moves, and deletes P0 nodes with stale-hash rejection",()=>{const base=parseStory(source),hash=storyDocumentHash(base);const inserted=insertP0Node(source,"statement_wait",{kind:"wait",durationRaw:"1s",id:"statement_wait_long",trailingMetadata:""},hash);expect(inserted.ok).toBe(true);if(!inserted.ok)return;const stale=updateP0Node(inserted.source,"statement_wait_long",{durationRaw:"2s"},hash);expect(stale).toMatchObject({ok:false,code:"STALE_DOCUMENT"});const updated=updateP0Node(inserted.source,"statement_wait_long",{durationRaw:"2s"},inserted.documentHash);expect(updated.ok).toBe(true);if(!updated.ok)return;const moved=moveP0Node(updated.source,"statement_wait_long","statement_narration",updated.documentHash);expect(moved.ok).toBe(true);if(!moved.ok)return;const removed=deleteP0Node(moved.source,"statement_wait_long",moved.documentHash);expect(removed.ok).toBe(true);if(!removed.ok)return;expect(semanticSnapshot(removed.storyDocument)).toEqual(semanticSnapshot(base));});
  it("inserts and moves P0 nodes before an explicit anchor",()=>{const ids=(document:ReturnType<typeof parseStory>)=>document.nodes.map((node)=>"id" in node?node.id:"statementId" in node?node.statementId:undefined).filter(Boolean);const inserted=insertP0NodeBefore(source,"statement_narration",{kind:"narration",statementId:"statement_before",textId:"text_before",textRaw:'"Before"',trailingMetadata:""});expect(inserted.ok).toBe(true);if(!inserted.ok)return;const insertedIds=ids(inserted.storyDocument);expect(insertedIds.indexOf("statement_before")+1).toBe(insertedIds.indexOf("statement_narration"));const moved=moveP0NodeBefore(inserted.source,"statement_wait","statement_before",inserted.documentHash);expect(moved.ok).toBe(true);if(!moved.ok)return;const movedIds=ids(moved.storyDocument);expect(movedIds.indexOf("statement_wait")+1).toBe(movedIds.indexOf("statement_before"));expect(movedIds.indexOf("statement_before")).toBeLessThan(movedIds.indexOf("statement_narration"));});
  it("updates one line incrementally and surfaces changed-line diagnostics before full validation",()=>{const state=createIncrementalStoryState(source),line=state.lines.findIndex((item)=>item.includes("wait 250ms"));const changed=updateIncrementalStoryLine(state,line,"wait 500ms @id(statement_wait)");expect(changed.needsFullValidation).toBe(true);expect(changed.storyDocument.nodes[line]).toMatchObject({kind:"wait",durationRaw:"500ms"});const invalid=updateIncrementalStoryLine(state,line,"wait someday @id(statement_wait)");expect(invalid.storyDocument.diagnostics).toContainEqual(expect.objectContaining({code:"MALFORMED_WAIT"}));});
});
