import { formatStory, semanticSnapshot } from "./formatter";
import type { CallNode, ChoiceNode, ChoiceOptionNode, ConditionNode, DialogueNode, DirectiveNode, EndNode, JumpNode, LabelNode, NarrationNode, ReturnNode, SetNode, SourceRange, StoryDocument, StorySyntaxNode, WaitNode } from "./model";
import { parseStory } from "./parser";

export type P0PatchErrorCode="SOURCE_INVALID"|"STALE_DOCUMENT"|"TARGET_NOT_FOUND"|"ANCHOR_NOT_FOUND"|"DUPLICATE_ID"|"MISSING_ID"|"INVALID_PATCH";
export type P0PatchResult={readonly ok:true;readonly changed:boolean;readonly source:string;readonly storyDocument:StoryDocument;readonly documentHash:string;readonly affectedIds:readonly string[]}|{readonly ok:false;readonly code:P0PatchErrorCode;readonly message:string};
export type P0EditableNode=Omit<DialogueNode,"range">|Omit<NarrationNode,"range">|Omit<ChoiceNode,"range">|Omit<ChoiceOptionNode,"range">|Omit<LabelNode,"range">|Omit<JumpNode,"range">|Omit<CallNode,"range">|Omit<ReturnNode,"range">|Omit<SetNode,"range">|Omit<ConditionNode,"range">|Omit<WaitNode,"range">|Omit<DirectiveNode,"range">|Omit<EndNode,"range">;
const zeroRange:SourceRange={start:{line:1,column:1,offset:0},end:{line:1,column:1,offset:0}};
export function p0NodeId(node:StorySyntaxNode|P0EditableNode):string|undefined{if(node.kind==="dialogue"||node.kind==="narration")return node.statementId;if("id" in node&&typeof node.id==="string")return node.id;return undefined;}
export function storyDocumentHash(storyDocument:StoryDocument):string{const source=JSON.stringify(semanticSnapshot(storyDocument));let hash=2166136261;for(let index=0;index<source.length;index++)hash=Math.imul(hash^source.charCodeAt(index),16777619);return (hash>>>0).toString(16).padStart(8,"0");}
const fail=(code:P0PatchErrorCode,message:string):P0PatchResult=>({ok:false,code,message});
function prepare(source:string,expectedDocumentHash?:string):{storyDocument:StoryDocument;hash:string}|P0PatchResult{const storyDocument=parseStory(source);if(storyDocument.diagnostics.some((item)=>item.severity==="error"))return fail("SOURCE_INVALID","Cannot patch a story with syntax errors");const hash=storyDocumentHash(storyDocument);if(expectedDocumentHash!==undefined&&hash!==expectedDocumentHash)return fail("STALE_DOCUMENT",`Expected story ${expectedDocumentHash}, current ${hash}`);return {storyDocument,hash};}
function finish(storyDocument:StoryDocument,source:string,affectedIds:readonly string[]):P0PatchResult{const formatted=formatStory(storyDocument),parsed=parseStory(formatted);if(parsed.diagnostics.some((item)=>item.severity==="error"))return fail("INVALID_PATCH","Patch produced an invalid story");return {ok:true,changed:formatted!==source,source:formatted,storyDocument:parsed,documentHash:storyDocumentHash(parsed),affectedIds};}
export function insertP0Node(source:string,afterId:string|null,node:P0EditableNode,expectedDocumentHash?:string):P0PatchResult{const prepared=prepare(source,expectedDocumentHash);if("ok" in prepared)return prepared;const id=p0NodeId(node);if(id===undefined)return fail("MISSING_ID","P0 editable nodes require a stable statement ID");if(prepared.storyDocument.nodes.some((item)=>p0NodeId(item)===id))return fail("DUPLICATE_ID",`Stable ID already exists: ${id}`);const at=afterId===null?prepared.storyDocument.nodes.length:prepared.storyDocument.nodes.findIndex((item)=>p0NodeId(item)===afterId)+1;if(afterId!==null&&at===0)return fail("ANCHOR_NOT_FOUND",`Anchor was not found: ${afterId}`);const nodes=[...prepared.storyDocument.nodes];nodes.splice(at,0,{...node,range:zeroRange} as StorySyntaxNode);return finish({...prepared.storyDocument,nodes},source,[id]);}
export function insertP0NodeBefore(source:string,beforeId:string,node:P0EditableNode,expectedDocumentHash?:string):P0PatchResult{const prepared=prepare(source,expectedDocumentHash);if("ok" in prepared)return prepared;const id=p0NodeId(node);if(id===undefined)return fail("MISSING_ID","P0 editable nodes require a stable statement ID");if(prepared.storyDocument.nodes.some((item)=>p0NodeId(item)===id))return fail("DUPLICATE_ID",`Stable ID already exists: ${id}`);const at=prepared.storyDocument.nodes.findIndex((item)=>p0NodeId(item)===beforeId);if(at<0)return fail("ANCHOR_NOT_FOUND",`Anchor was not found: ${beforeId}`);const nodes=[...prepared.storyDocument.nodes];nodes.splice(at,0,{...node,range:zeroRange} as StorySyntaxNode);return finish({...prepared.storyDocument,nodes},source,[id]);}
export function updateP0Node(source:string,targetId:string,patch:Readonly<Record<string,unknown>>,expectedDocumentHash?:string):P0PatchResult{const prepared=prepare(source,expectedDocumentHash);if("ok" in prepared)return prepared;const at=prepared.storyDocument.nodes.findIndex((item)=>p0NodeId(item)===targetId);if(at<0)return fail("TARGET_NOT_FOUND",`Target was not found: ${targetId}`);const current=prepared.storyDocument.nodes[at]!;if("kind" in patch&&patch.kind!==current.kind)return fail("INVALID_PATCH","Patch cannot change node kind");if(("id" in patch&&patch.id!==targetId)||("statementId" in patch&&patch.statementId!==targetId))return fail("INVALID_PATCH","Patch cannot change stable ID");const nodes=[...prepared.storyDocument.nodes];nodes[at]={...current,...patch,kind:current.kind,range:current.range} as StorySyntaxNode;return finish({...prepared.storyDocument,nodes},source,[targetId]);}
export function deleteP0Node(source:string,targetId:string,expectedDocumentHash?:string):P0PatchResult{const prepared=prepare(source,expectedDocumentHash);if("ok" in prepared)return prepared;const at=prepared.storyDocument.nodes.findIndex((item)=>p0NodeId(item)===targetId);if(at<0)return fail("TARGET_NOT_FOUND",`Target was not found: ${targetId}`);const nodes=prepared.storyDocument.nodes.filter((_,index)=>index!==at);return finish({...prepared.storyDocument,nodes},source,[targetId]);}
export function moveP0Node(source:string,targetId:string,afterId:string,expectedDocumentHash?:string):P0PatchResult{const prepared=prepare(source,expectedDocumentHash);if("ok" in prepared)return prepared;if(targetId===afterId)return fail("INVALID_PATCH","Target cannot move after itself");const from=prepared.storyDocument.nodes.findIndex((item)=>p0NodeId(item)===targetId),anchor=prepared.storyDocument.nodes.findIndex((item)=>p0NodeId(item)===afterId);if(from<0)return fail("TARGET_NOT_FOUND",`Target was not found: ${targetId}`);if(anchor<0)return fail("ANCHOR_NOT_FOUND",`Anchor was not found: ${afterId}`);const nodes=[...prepared.storyDocument.nodes],item=nodes.splice(from,1)[0]!;const nextAnchor=nodes.findIndex((node)=>p0NodeId(node)===afterId);nodes.splice(nextAnchor+1,0,item);return finish({...prepared.storyDocument,nodes},source,[targetId]);}
export function moveP0NodeBefore(source:string,targetId:string,beforeId:string,expectedDocumentHash?:string):P0PatchResult{const prepared=prepare(source,expectedDocumentHash);if("ok" in prepared)return prepared;if(targetId===beforeId)return fail("INVALID_PATCH","Target cannot move before itself");const from=prepared.storyDocument.nodes.findIndex((item)=>p0NodeId(item)===targetId),anchor=prepared.storyDocument.nodes.findIndex((item)=>p0NodeId(item)===beforeId);if(from<0)return fail("TARGET_NOT_FOUND",`Target was not found: ${targetId}`);if(anchor<0)return fail("ANCHOR_NOT_FOUND",`Anchor was not found: ${beforeId}`);const nodes=[...prepared.storyDocument.nodes],item=nodes.splice(from,1)[0]!;const nextAnchor=nodes.findIndex((node)=>p0NodeId(node)===beforeId);nodes.splice(nextAnchor,0,item);return finish({...prepared.storyDocument,nodes},source,[targetId]);}
