import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe,expect,it } from "vitest";
import { loadProject,migrateS0Project,saveProject,sha256,type ProjectFiles,type ProjectReference,type ProjectTrustedSourceCommit,type ProjectWorkspace,type S0Project } from "@world-studio/project-domain";
import { compileProjectIncremental } from "./compiler";
import { compileProjectWorkspace, createProjectCompilerCacheArtifact, verifyProjectCompilerCacheArtifact } from "./compiler-cache-artifact";

function fixture(){const source=JSON.parse(readFileSync(join(process.cwd(),"fixtures","projects","branching","project.s0.json"),"utf8")) as S0Project;const project=loadProject(migrateS0Project(source).files);return {project,files:saveProject(project)};}
class CacheWorkspace implements ProjectWorkspace {readonly reference:ProjectReference={referenceId:"cache",hostKind:"memory-test",displayLocation:"memory",permissionKey:"cache"};files:Record<string,string>;derived:string|null=null;inventory="inventory-a";fullReads=0;invalidTrustedCommit=false;constructor(files:ProjectFiles,readonly trusted=false){this.files={...files};if(trusted)this.inventory=this.commit().version;}private commit():ProjectTrustedSourceCommit{const generation=1,entries=Object.entries(this.files).sort(([left],[right])=>left.localeCompare(right)).map(([path,value])=>({path,size:new TextEncoder().encode(value).byteLength,modifiedAtMs:1,sha256:sha256(value)}));const version=sha256(JSON.stringify({schemaVersion:1,generation,files:entries}));return {schemaVersion:1,version:this.invalidTrustedCommit?sha256("forged"):version,generation,files:entries};}async readFiles(){this.fullReads+=1;return {files:this.files,version:this.inventory};}async readTrustedSourceCommit():Promise<ProjectTrustedSourceCommit|null>{return this.trusted?this.commit():null;}async listProjectFiles(){return {files:Object.entries(this.files).map(([path,value])=>({path,size:value.length,modifiedAtMs:1})),version:this.inventory};}async readDerivedFile(){return this.derived;}async writeDerivedFile(_path:string,value:string){this.derived=value;}async clearDerivedFiles(){this.derived=null;}async writeFiles(files:ProjectFiles){this.files={...files};this.derived=null;return {version:this.inventory};}}

describe("project compiler disposable cache artifact",()=>{
  it("reuses every scene only after inventory and source hashes validate",()=>{const {project,files}=fixture();const first=compileProjectIncremental(project);const artifact=createProjectCompilerCacheArtifact(files,"inventory-a",first.cache);const verified=verifyProjectCompilerCacheArtifact(artifact,files,"inventory-a");expect(verified.status).toBe("valid");if(verified.status!=="valid")return;const second=compileProjectIncremental(project,{previousCache:verified.cache});expect(second.stats.compiledSceneIds).toEqual([]);expect(second.stats.reusedSceneIds).toEqual(project.scenes.map((scene)=>scene.id).sort());});
  it("rejects inventory drift, same-inventory source tampering, incompatible versions, and corrupt envelopes",()=>{const {project,files}=fixture();const artifact=createProjectCompilerCacheArtifact(files,"inventory-a",compileProjectIncremental(project).cache);expect(verifyProjectCompilerCacheArtifact(artifact,files,"inventory-b")).toMatchObject({status:"invalid",reason:"inventory-mismatch"});const scriptPath=project.scenes[0]!.scriptPath;expect(verifyProjectCompilerCacheArtifact(artifact,{...files,[scriptPath]:`${files[scriptPath]} `},"inventory-a")).toMatchObject({status:"invalid",reason:"source-mismatch"});const parsed=JSON.parse(artifact) as Record<string,unknown>;expect(verifyProjectCompilerCacheArtifact(JSON.stringify({...parsed,compilerVersion:"old"}),files,"inventory-a")).toMatchObject({status:"invalid",reason:"incompatible"});expect(verifyProjectCompilerCacheArtifact(`${artifact}broken`,files,"inventory-a")).toMatchObject({status:"invalid",reason:"corrupt"});});
  it("misses, reuses, and fail-closed rebuilds through the workspace cache flow",async()=>{const {project,files}=fixture();const workspace=new CacheWorkspace(files);const first=await compileProjectWorkspace(workspace);expect(first.cacheStatus).toBe("miss");expect(first.compilation.stats.compiledSceneIds).toEqual(project.scenes.map((scene)=>scene.id).sort());const second=await compileProjectWorkspace(workspace);expect(second.cacheStatus).toBe("hit");expect(second.compilation.stats.compiledSceneIds).toEqual([]);const scriptPath=project.scenes[0]!.scriptPath;workspace.files[scriptPath]=`${workspace.files[scriptPath]} `;const rebuilt=await compileProjectWorkspace(workspace);expect(rebuilt.cacheStatus).toBe("source-mismatch");expect(rebuilt.compilation.stats.compiledSceneIds).toEqual(project.scenes.map((scene)=>scene.id).sort());});
  it("reopens a trusted source commit without reading source-store bodies",async()=>{const {project,files}=fixture();const workspace=new CacheWorkspace(files,true);const first=await compileProjectWorkspace(workspace);expect(first.cacheStatus).toBe("miss");expect(workspace.fullReads).toBe(1);const reopened=await compileProjectWorkspace(workspace);expect(reopened.cacheStatus).toBe("hit");expect(reopened.compilation.stats.reusedSceneIds).toEqual(project.scenes.map((scene)=>scene.id).sort());expect(reopened.files).toEqual(files);expect(workspace.fullReads).toBe(1);});
  it("falls back to verified source bodies when the trusted snapshot envelope is corrupt",async()=>{const {files}=fixture();const workspace=new CacheWorkspace(files,true);await compileProjectWorkspace(workspace);const artifact=JSON.parse(workspace.derived!) as Record<string,unknown>;const snapshot={...(artifact.sourceFiles as Record<string,string>)};snapshot["world.project.json"]=`${snapshot["world.project.json"]} `;workspace.derived=JSON.stringify({...artifact,sourceFiles:snapshot});const rebuilt=await compileProjectWorkspace(workspace);expect(rebuilt.cacheStatus).toBe("corrupt");expect(workspace.fullReads).toBe(2);const reopened=await compileProjectWorkspace(workspace);expect(reopened.cacheStatus).toBe("hit");expect(workspace.fullReads).toBe(2);});
  it("refuses a forged trusted commit and uses the verified full-read path",async()=>{const {files}=fixture();const workspace=new CacheWorkspace(files,true);await compileProjectWorkspace(workspace);workspace.invalidTrustedCommit=true;const reopened=await compileProjectWorkspace(workspace);expect(reopened.cacheStatus).toBe("hit");expect(workspace.fullReads).toBe(2);});
});
