import { loadProject,sha256,type CanonicalProject,type JsonValue,type ProjectFiles,type ProjectWorkspace } from "@world-studio/project-domain";
import { canonicalJson } from "./canonical-json";
import { compileProjectIncremental } from "./compiler";
import { PROJECT_COMPILER_VERSION,RUNTIME_IR_VERSION,type CompileProfile,type CompileProjectResult,type CompilerSceneCacheEntryV1,type ProjectCompilerCacheV1 } from "./types";

export const PROJECT_COMPILER_CACHE_PATH=".world-cache/compiler-v1.json";
export type ProjectCompilerCacheVerification={readonly status:"valid";readonly cache:ProjectCompilerCacheV1}|{readonly status:"invalid";readonly reason:"corrupt"|"incompatible"|"inventory-mismatch"|"source-mismatch"};
interface CachePayload {readonly schemaVersion:1;readonly compilerVersion:typeof PROJECT_COMPILER_VERSION;readonly irVersion:typeof RUNTIME_IR_VERSION;readonly inventoryVersion:string;readonly sourceHashes:Readonly<Record<string,string>>;readonly cache:ProjectCompilerCacheV1;}
const record=(value:unknown):value is Record<string,unknown>=>value!==null&&!Array.isArray(value)&&typeof value==="object";
const hashPattern=/^[0-9a-f]{64}$/u;
const sourceHashes=(files:ProjectFiles):Readonly<Record<string,string>>=>Object.fromEntries(Object.entries(files).sort(([left],[right])=>left.localeCompare(right)).map(([path,value])=>[path,sha256(value)]));
const artifactHash=(payload:CachePayload):string=>sha256(canonicalJson(payload as unknown as JsonValue));
function validEntry(value:unknown):value is CompilerSceneCacheEntryV1 {if(!record(value)||typeof value.inputHash!=="string"||typeof value.outputHash!=="string"||!record(value.scene)||typeof value.scene.sceneId!=="string"||!Array.isArray(value.scene.instructions))return false;return ["sourceEntries","diagnostics","targetSceneIds","endings","galleryAssetIds","musicAssetIds"].every((field)=>Array.isArray(value[field]));}
function validCache(value:unknown):value is ProjectCompilerCacheV1 {return record(value)&&value.schemaVersion===1&&value.compilerVersion===PROJECT_COMPILER_VERSION&&value.irVersion===RUNTIME_IR_VERSION&&typeof value.catalogInputHash==="string"&&record(value.scenes)&&Object.values(value.scenes).every(validEntry);}
export function createProjectCompilerCacheArtifact(files:ProjectFiles,inventoryVersion:string,cache:ProjectCompilerCacheV1):string {const payload:CachePayload={schemaVersion:1,compilerVersion:PROJECT_COMPILER_VERSION,irVersion:RUNTIME_IR_VERSION,inventoryVersion,sourceHashes:sourceHashes(files),cache};return `${canonicalJson({...payload,artifactHash:artifactHash(payload)} as unknown as JsonValue)}\n`;}
export function verifyProjectCompilerCacheArtifact(source:string,files:ProjectFiles,inventoryVersion:string):ProjectCompilerCacheVerification {let value:unknown;try{value=JSON.parse(source);}catch{return {status:"invalid",reason:"corrupt"};}if(!record(value)||value.schemaVersion!==1||value.compilerVersion!==PROJECT_COMPILER_VERSION||value.irVersion!==RUNTIME_IR_VERSION)return {status:"invalid",reason:"incompatible"};if(value.inventoryVersion!==inventoryVersion)return {status:"invalid",reason:"inventory-mismatch"};if(!record(value.sourceHashes)||Object.values(value.sourceHashes).some((hash)=>typeof hash!=="string"||!hashPattern.test(hash))||!validCache(value.cache)||typeof value.artifactHash!=="string")return {status:"invalid",reason:"corrupt"};const payload:CachePayload={schemaVersion:1,compilerVersion:PROJECT_COMPILER_VERSION,irVersion:RUNTIME_IR_VERSION,inventoryVersion,sourceHashes:value.sourceHashes as Record<string,string>,cache:value.cache};if(value.artifactHash!==artifactHash(payload))return {status:"invalid",reason:"corrupt"};const expected=sourceHashes(files),actual=payload.sourceHashes;if(Object.keys(actual).length!==Object.keys(expected).length||Object.entries(expected).some(([path,hash])=>actual[path]!==hash))return {status:"invalid",reason:"source-mismatch"};return {status:"valid",cache:payload.cache};}

export type WorkspaceCompilerCacheStatus="unsupported"|"miss"|"hit"|Exclude<ProjectCompilerCacheVerification,{status:"valid"}>["reason"];
export interface WorkspaceCompileResult {readonly project:CanonicalProject;readonly files:ProjectFiles;readonly hostVersion:string;readonly inventoryVersion?:string;readonly cacheStatus:WorkspaceCompilerCacheStatus;readonly compilation:CompileProjectResult;}
export async function compileProjectWorkspace(workspace:ProjectWorkspace,profile:CompileProfile="debug"):Promise<WorkspaceCompileResult>{const supported=workspace.listProjectFiles!==undefined&&workspace.readDerivedFile!==undefined&&workspace.writeDerivedFile!==undefined;const before=supported?await workspace.listProjectFiles!():undefined;const source=await workspace.readFiles();const project=loadProject(source.files);if(!supported){return {project,files:source.files,hostVersion:source.version,cacheStatus:"unsupported",compilation:compileProjectIncremental(project,{profile})};}const afterRead=await workspace.listProjectFiles!();if(before!.version!==afterRead.version)throw new Error("Project files changed while reading Compiler cache input");const artifact=await workspace.readDerivedFile!(PROJECT_COMPILER_CACHE_PATH);const verified=artifact===null?null:verifyProjectCompilerCacheArtifact(artifact,source.files,afterRead.version);const cacheStatus:WorkspaceCompilerCacheStatus=artifact===null?"miss":verified?.status==="valid"?"hit":verified!.reason;const compilation=compileProjectIncremental(project,{profile,...(verified?.status==="valid"?{previousCache:verified.cache}:{})});const afterCompile=await workspace.listProjectFiles!();if(afterCompile.version!==afterRead.version)throw new Error("Project files changed while compiling derived cache");await workspace.writeDerivedFile!(PROJECT_COMPILER_CACHE_PATH,createProjectCompilerCacheArtifact(source.files,afterCompile.version,compilation.cache));return {project,files:source.files,hostVersion:source.version,inventoryVersion:afterCompile.version,cacheStatus,compilation};}
