import { loadProject, probeProject, saveProject, semanticHash } from "./codec";
import { exportProjectZip, importProjectZip } from "./project-archive";
import { createStableId } from "./stable-id";
import type { CanonicalProject, ProjectFiles } from "./types";

export type ProjectHostKind="windows-directory"|"web-file-system"|"web-opfs"|"memory-test";
export interface ProjectReference { readonly referenceId:string; readonly hostKind:ProjectHostKind; readonly displayLocation:string; readonly permissionKey:string; }
export interface ProjectWorkspace { readonly reference:ProjectReference; readFiles():Promise<{readonly files:ProjectFiles;readonly version:string}>; writeFiles(files:ProjectFiles,expectedVersion:string|null):Promise<{readonly version:string}>; }
export interface RecentProject { readonly reference:ProjectReference; readonly projectId:string; readonly title:string; readonly lastOpenedAtMs:number; }
export interface RecentProjectStore { load():Promise<readonly RecentProject[]>; save(items:readonly RecentProject[]):Promise<void>; }
export interface ProjectLifecycleSession { readonly project:CanonicalProject|null; readonly projectId:string; readonly title:string; readonly schemaVersion:number; readonly reference:ProjectReference; readonly hostVersion:string|null; readonly baseHash:string; readonly baseFiles:ProjectFiles; readonly dirty:boolean; readonly recovery:"clean"|"recovered"; readonly access:"editable"|"read-only"; readonly readOnlyReason?:string; }
export type ExternalChangeResult={readonly status:"unchanged";readonly session:ProjectLifecycleSession}|{readonly status:"reloaded";readonly changedPaths:readonly string[];readonly session:ProjectLifecycleSession}|{readonly status:"conflict";readonly changedPaths:readonly string[];readonly baseHash:string;readonly localHash:string;readonly externalHash:string;readonly external:CanonicalProject};
export class ProjectLifecycleError extends Error { constructor(readonly code:"FUTURE_READ_ONLY"|"WRITE_CONFLICT"|"INVALID_TEMPLATE"|"INVALID_PROJECT",message:string){super(message);this.name="ProjectLifecycleError";} }

export function createProjectTemplate(title:string,durableEntropy:string):CanonicalProject {
  if(title.trim()==="")throw new ProjectLifecycleError("INVALID_TEMPLATE","Project title must not be empty");const projectId=createStableId("project",durableEntropy),chapterId=createStableId("chapter",`${durableEntropy}/chapter`),sceneId=createStableId("scene",`${durableEntropy}/scene`),statementId=createStableId("statement",`${durableEntropy}/statement`),chapterPath=`chapters/${chapterId}.json`,scenePath=`scenes/${sceneId}.json`,scriptPath=`scripts/${sceneId}.json`,layoutPath=`layouts/${sceneId}.json`;
  return {mode:"editable",manifest:{schemaVersion:1,fileVersion:"1.0.0",projectId,title:title.trim(),defaultLocale:"und",entrySceneId:sceneId,chapterPaths:[chapterPath],charactersPath:"domain/characters.json",variablesPath:"domain/variables.json",assetsPath:"domain/assets.json",localizationPath:"localization/catalog.json",settingsPath:"settings/project.json",uiPath:"ui/screens.json",pluginsPath:"plugins/plugins.json",testRoutesPath:"tests/routes.json"},chapters:[{schemaVersion:1,id:chapterId,title:"Main",scenePaths:[scenePath]}],scenes:[{schemaVersion:1,id:sceneId,title:"Start",scriptPath,layoutPath}],characters:{schemaVersion:1,characters:[]},variables:{schemaVersion:1,variables:[]},assets:{schemaVersion:1,assets:[]},localization:{schemaVersion:1,locales:[]},settings:{schemaVersion:1,values:{}},ui:{schemaVersion:1,screens:[]},plugins:{schemaVersion:1,plugins:[]},testRoutes:{schemaVersion:1,routes:[]},scripts:{[sceneId]:{schemaVersion:1,sceneId,statements:[{id:statementId,kind:"end",endingName:"Ending"}]}},layouts:{[sceneId]:{schemaVersion:1,sceneId,nodes:[]}}};
}
export async function rememberRecent(store:RecentProjectStore,session:ProjectLifecycleSession,nowMs:number):Promise<void>{const current=await store.load();const item:RecentProject={reference:session.reference,projectId:session.projectId,title:session.title,lastOpenedAtMs:nowMs};await store.save([item,...current.filter(value=>value.reference.referenceId!==session.reference.referenceId)].slice(0,20));}
export async function createProject(workspace:ProjectWorkspace,title:string,durableEntropy:string):Promise<ProjectLifecycleSession>{const project=createProjectTemplate(title,durableEntropy),baseFiles=saveProject(project);const result=await workspace.writeFiles(baseFiles,null);return {project,projectId:project.manifest.projectId,title:project.manifest.title,schemaVersion:1,reference:workspace.reference,hostVersion:result.version,baseHash:semanticHash(project),baseFiles,dirty:false,recovery:"clean",access:"editable"};}
export async function openProject(workspace:ProjectWorkspace):Promise<ProjectLifecycleSession>{const snapshot=await workspace.readFiles();const probe=probeProject(snapshot.files);if(probe.status==="future-read-only")return {project:null,projectId:probe.projectId??"unknown_project",title:probe.title??"Future Project",schemaVersion:probe.schemaVersion,reference:workspace.reference,hostVersion:snapshot.version,baseHash:"",baseFiles:snapshot.files,dirty:false,recovery:"clean",access:"read-only",readOnlyReason:`Project schema ${probe.schemaVersion} requires a newer editor`};const project=loadProject(snapshot.files);return {project,projectId:project.manifest.projectId,title:project.manifest.title,schemaVersion:1,reference:workspace.reference,hostVersion:snapshot.version,baseHash:semanticHash(project),baseFiles:snapshot.files,dirty:false,recovery:"clean",access:"editable"};}
export function markProjectDirty(session:ProjectLifecycleSession,project:CanonicalProject):ProjectLifecycleSession{return {...session,project,projectId:project.manifest.projectId,title:project.manifest.title,dirty:semanticHash(project)!==session.baseHash};}
export async function saveLifecycleProject(workspace:ProjectWorkspace,session:ProjectLifecycleSession):Promise<ProjectLifecycleSession>{if(session.access!=="editable"||session.project===null)throw new ProjectLifecycleError("FUTURE_READ_ONLY",session.readOnlyReason??"Project is read-only");try{const baseFiles=saveProject(session.project),result=await workspace.writeFiles(baseFiles,session.hostVersion);const hash=semanticHash(session.project);return {...session,hostVersion:result.version,baseHash:hash,baseFiles,dirty:false};}catch(error){throw new ProjectLifecycleError("WRITE_CONFLICT",error instanceof Error?error.message:String(error));}}
export function exportLifecycleProject(session:ProjectLifecycleSession):Uint8Array{if(session.project===null)throw new ProjectLifecycleError("FUTURE_READ_ONLY","Read-only future projects cannot be exported through the current codec");return exportProjectZip(saveProject(session.project));}
export function importLifecycleProject(archive:Uint8Array):CanonicalProject{return loadProject(importProjectZip(archive));}
function changedPaths(base:ProjectFiles,next:ProjectFiles):readonly string[]{return [...new Set([...Object.keys(base),...Object.keys(next)])].filter((path)=>base[path]!==next[path]).sort();}
export async function detectExternalChange(workspace:ProjectWorkspace,session:ProjectLifecycleSession):Promise<ExternalChangeResult>{if(session.project===null)return {status:"unchanged",session};const snapshot=await workspace.readFiles(),external=loadProject(snapshot.files),externalHash=semanticHash(external),localHash=semanticHash(session.project),paths=changedPaths(session.baseFiles,snapshot.files);if(externalHash===session.baseHash)return {status:"unchanged",session};if(!session.dirty||localHash===session.baseHash)return {status:"reloaded",changedPaths:paths,session:{...session,project:external,projectId:external.manifest.projectId,title:external.manifest.title,hostVersion:snapshot.version,baseHash:externalHash,baseFiles:snapshot.files,dirty:false}};return {status:"conflict",changedPaths:paths,baseHash:session.baseHash,localHash,externalHash,external};}
