import { loadProject, saveProject, semanticHash } from "./codec";
import type { CanonicalProject, JsonObject, ProjectFiles } from "./types";

interface CommandBase { readonly commandId: string; readonly expectedRevision: number; }
export type ProjectCommand =
  | (CommandBase & { readonly kind: "chapter.create"; readonly chapterId: string; readonly title: string; readonly index?: number })
  | (CommandBase & { readonly kind: "chapter.rename"; readonly chapterId: string; readonly title: string })
  | (CommandBase & { readonly kind: "chapter.delete"; readonly chapterId: string })
  | (CommandBase & { readonly kind: "chapter.move"; readonly chapterId: string; readonly index: number })
  | (CommandBase & { readonly kind: "scene.create"; readonly chapterId: string; readonly sceneId: string; readonly title: string; readonly index?: number; readonly makeEntry?: boolean })
  | (CommandBase & { readonly kind: "scene.rename"; readonly sceneId: string; readonly title: string })
  | (CommandBase & { readonly kind: "scene.delete"; readonly sceneId: string; readonly replacementSceneId?: string })
  | (CommandBase & { readonly kind: "scene.move"; readonly sceneId: string; readonly chapterId: string; readonly index: number })
  | (CommandBase & { readonly kind: "scene.set-entry"; readonly sceneId: string })
  | (CommandBase & { readonly kind: "character.create"; readonly character: JsonObject })
  | (CommandBase & { readonly kind: "character.rename"; readonly characterId: string; readonly displayName: string })
  | (CommandBase & { readonly kind: "character.update"; readonly characterId: string; readonly patch: JsonObject })
  | (CommandBase & { readonly kind: "character.delete"; readonly characterId: string; readonly replacementCharacterId?: string })
  | (CommandBase & { readonly kind: "character.move"; readonly characterId: string; readonly index: number })
  | (CommandBase & { readonly kind: "variable.create"; readonly variable: JsonObject })
  | (CommandBase & { readonly kind: "variable.rename"; readonly variableId: string; readonly name: string })
  | (CommandBase & { readonly kind: "variable.update"; readonly variableId: string; readonly patch: JsonObject })
  | (CommandBase & { readonly kind: "variable.delete"; readonly variableId: string; readonly replacementVariableId?: string })
  | (CommandBase & { readonly kind: "variable.move"; readonly variableId: string; readonly index: number })
  | (CommandBase & { readonly kind: "asset.create"; readonly asset: JsonObject })
  | (CommandBase & { readonly kind: "asset.rename"; readonly assetId: string; readonly name: string })
  | (CommandBase & { readonly kind: "asset.delete"; readonly assetId: string })
  | (CommandBase & { readonly kind: "asset.move"; readonly assetId: string; readonly index: number })
  | (CommandBase & { readonly kind: "statement.insert"; readonly sceneId: string; readonly statement: JsonObject; readonly index?: number })
  | (CommandBase & { readonly kind: "statement.update"; readonly sceneId: string; readonly statementId: string; readonly patch: JsonObject })
  | (CommandBase & { readonly kind: "statement.delete"; readonly sceneId: string; readonly statementId: string })
  | (CommandBase & { readonly kind: "statement.move"; readonly sceneId: string; readonly statementId: string; readonly index: number });

export type ProjectServiceErrorCode = "STALE_REVISION" | "DUPLICATE_COMMAND" | "DUPLICATE_ID" | "NOT_FOUND" | "INVALID_COMMAND" | "REFERENCE_CONFLICT" | "INVALID_PROJECT";
export interface ProjectServiceError { readonly code: ProjectServiceErrorCode; readonly commandId: string; readonly message: string; readonly entityId?: string; }
export interface ChangeSet { readonly commandIds: readonly string[]; readonly baseRevision: number; readonly revision: number; readonly beforeHash: string; readonly afterHash: string; readonly changedEntityIds: readonly string[]; }
interface HistoryEntry { readonly project: CanonicalProject; readonly changeSet: ChangeSet; }
export interface ProjectServiceState { readonly project: CanonicalProject; readonly revision: number; readonly appliedCommandIds: ReadonlySet<string>; readonly undoStack: readonly HistoryEntry[]; readonly redoStack: readonly HistoryEntry[]; readonly lastChangeSet?: ChangeSet; }
export type ProjectServiceResult = { readonly ok: true; readonly state: ProjectServiceState; readonly changeSet: ChangeSet } | { readonly ok: false; readonly state: ProjectServiceState; readonly error: ProjectServiceError };

const ID = /^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$/;
const clone = <T>(value: T): T => structuredClone(value);
const fail = (state: ProjectServiceState, commandId: string, code: ProjectServiceErrorCode, message: string, entityId?: string): ProjectServiceResult => ({ ok: false, state, error: { code, commandId, message, ...(entityId === undefined ? {} : { entityId }) } });
function index(value: number | undefined, length: number): number { const result=value??length; if(!Number.isInteger(result)||result<0||result>length) throw new Error("index is outside the collection"); return result; }
function entityId(value: JsonObject, label: string): string { if(typeof value.id!=="string"||!ID.test(value.id)) throw new Error(`${label}.id is invalid`); return value.id; }
function insert<T>(items: readonly T[], item: T, at?: number): T[] { const next=[...items]; next.splice(index(at,next.length),0,item); return next; }
function move<T>(items: readonly T[], from: number, to: number): T[] { if(from<0) throw new Error("entity was not found"); const next=[...items]; const [item]=next.splice(from,1); if(item===undefined) throw new Error("entity was not found"); next.splice(index(to,next.length),0,item); return next; }
function hasId(project: CanonicalProject, id: string): boolean { return project.manifest.projectId===id||project.chapters.some(x=>x.id===id)||project.scenes.some(x=>x.id===id)||[...project.characters.characters,...project.variables.variables,...project.assets.assets,...Object.values(project.scripts).flatMap(x=>x.statements)].some(x=>x.id===id||x.textId===id); }
function references(value: unknown, id: string, ignoredKeys = new Set(["id","textId"])): boolean { if(Array.isArray(value)) return value.some(item=>references(item,id,ignoredKeys)); if(value!==null&&typeof value==="object") return Object.entries(value).some(([key,item])=>(!ignoredKeys.has(key)&&(key.endsWith("Id")||key.endsWith("Ids"))&&(item===id||(Array.isArray(item)&&item.includes(id))))||references(item,id,ignoredKeys)); return false; }
function replaceReferences(value: unknown, sourceId: string, replacementId: string, key = ""): unknown { if(Array.isArray(value))return value.map((item)=>key.endsWith("Ids")&&item===sourceId?replacementId:replaceReferences(item,sourceId,replacementId,key));if(value!==null&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([childKey,item])=>[childKey,childKey!=="id"&&childKey!=="textId"&&childKey.endsWith("Id")&&item===sourceId?replacementId:replaceReferences(item,sourceId,replacementId,childKey)]));return value; }
function replaceAt<T>(items: readonly T[], at: number, value: T): T[] { const next=[...items];next[at]=value;return next; }
function collectionCommand(items: readonly JsonObject[], command: ProjectCommand, noun: "character"|"variable"|"asset"): {items:readonly JsonObject[];changed:string} {
  const data = command as unknown as Record<string, unknown>;
  const create=`${noun}.create`,rename=`${noun}.rename`,remove=`${noun}.delete`,reorder=`${noun}.move`;
  if(command.kind===create){const value=data[noun];if(value===null||typeof value!=="object"||Array.isArray(value))throw new Error(`${noun} is invalid`);const object=value as JsonObject;const id=entityId(object,noun);return {items:insert(items,object),changed:id};}
  const id=data[`${noun}Id`]; if(typeof id!=="string")throw new Error(`${noun} ID is invalid`);const at=items.findIndex(item=>item.id===id); if(at<0)throw new Error(`${noun} ${id} was not found`);
  if(command.kind===rename){const field=noun==="character"?"displayName":"name";const value=data[field];if(typeof value!=="string"||value.trim()==="")throw new Error(`${field} is empty`);return {items:replaceAt(items,at,{...items[at], [field]:value}),changed:id};}
  if(command.kind===`${noun}.update`){const patch=data.patch;if(patch===null||typeof patch!=="object"||Array.isArray(patch))throw new Error(`${noun} patch is invalid`);return {items:replaceAt(items,at,{...items[at],...(patch as JsonObject),id}),changed:id};}
  if(command.kind===remove)return {items:items.filter((_,i)=>i!==at),changed:id};
  if(command.kind===reorder){const target=data.index;if(typeof target!=="number")throw new Error("index is invalid");return {items:move(items,at,target),changed:id};}
  throw new Error("unsupported collection command");
}

function applyOne(project: CanonicalProject, command: ProjectCommand): {project:CanonicalProject;changed:string} {
  const data = command as unknown as Record<string, unknown>;
  if(!ID.test(command.commandId))throw new Error("commandId is invalid");
  if(command.kind.endsWith(".create")){const candidate=command.kind==="chapter.create"?command.chapterId:command.kind==="scene.create"?command.sceneId:command.kind==="character.create"?command.character.id:command.kind==="variable.create"?command.variable.id:command.kind==="asset.create"?command.asset.id:undefined;if(typeof candidate==="string"&&hasId(project,candidate))throw new Error(`duplicate ID ${candidate}`);}
  if(command.kind.startsWith("character.")){let nextProject=project;if(command.kind==="character.delete"&&references(project,command.characterId)){if(command.replacementCharacterId===undefined)throw new Error(`referenced entity ${command.characterId}`);if(command.replacementCharacterId===command.characterId||!project.characters.characters.some((item)=>item.id===command.replacementCharacterId))throw new Error(`character ${command.replacementCharacterId} was not found`);nextProject=replaceReferences(project,command.characterId,command.replacementCharacterId) as CanonicalProject;}const result=collectionCommand(nextProject.characters.characters,command,"character");return {project:{...nextProject,characters:{...nextProject.characters,characters:result.items}},changed:result.changed};}
  if(command.kind.startsWith("variable.")){let nextProject=project;if(command.kind==="variable.delete"&&references(project,command.variableId)){if(command.replacementVariableId===undefined)throw new Error(`referenced entity ${command.variableId}`);if(command.replacementVariableId===command.variableId||!project.variables.variables.some((item)=>item.id===command.replacementVariableId))throw new Error(`variable ${command.replacementVariableId} was not found`);nextProject=replaceReferences(project,command.variableId,command.replacementVariableId) as CanonicalProject;}const result=collectionCommand(nextProject.variables.variables,command,"variable");return {project:{...nextProject,variables:{...nextProject.variables,variables:result.items}},changed:result.changed};}
  if(command.kind.startsWith("asset.")){const result=collectionCommand(project.assets.assets,command,"asset");if(command.kind==="asset.delete"&&references(project,result.changed))throw new Error(`referenced entity ${result.changed}`);return {project:{...project,assets:{...project.assets,assets:result.items}},changed:result.changed};}
  if(command.kind==="chapter.create"){if(!ID.test(command.chapterId)||command.title.trim()==="")throw new Error("chapter input is invalid");const path=`chapters/${command.chapterId}.json`;const at=index(command.index,project.chapters.length);return {project:{...project,manifest:{...project.manifest,chapterPaths:insert(project.manifest.chapterPaths,path,at)},chapters:insert(project.chapters,{schemaVersion:1,id:command.chapterId,title:command.title,scenePaths:[]},at)},changed:command.chapterId};}
  const chapterAt="chapterId" in command?project.chapters.findIndex(x=>x.id===command.chapterId):-1;
  if(command.kind.startsWith("chapter.")&&chapterAt<0)throw new Error(`chapter ${"chapterId" in command?command.chapterId:""} was not found`);
  if(command.kind==="chapter.rename")return {project:{...project,chapters:replaceAt(project.chapters,chapterAt,{...project.chapters[chapterAt]!,title:command.title})},changed:command.chapterId};
  if(command.kind==="chapter.delete"){if(project.chapters[chapterAt]!.scenePaths.length>0)throw new Error(`referenced entity ${command.chapterId}`);return {project:{...project,manifest:{...project.manifest,chapterPaths:project.manifest.chapterPaths.filter((_,i)=>i!==chapterAt)},chapters:project.chapters.filter((_,i)=>i!==chapterAt)},changed:command.chapterId};}
  if(command.kind==="chapter.move")return {project:{...project,manifest:{...project.manifest,chapterPaths:move(project.manifest.chapterPaths,chapterAt,command.index)},chapters:move(project.chapters,chapterAt,command.index)},changed:command.chapterId};
  if(command.kind==="scene.create"){if(chapterAt<0||!ID.test(command.sceneId)||command.title.trim()==="")throw new Error("scene input is invalid");const scenePath=`scenes/${command.sceneId}.json`,scriptPath=`scripts/${command.sceneId}.json`,layoutPath=`layouts/${command.sceneId}.json`;const chapter=project.chapters[chapterAt]!;const sceneIndex=index(command.index,chapter.scenePaths.length);const flatIndex=project.chapters.slice(0,chapterAt).reduce((sum,item)=>sum+item.scenePaths.length,0)+sceneIndex;const nextChapter={...chapter,scenePaths:insert(chapter.scenePaths,scenePath,sceneIndex)};return {project:{...project,manifest:{...project.manifest,...((project.scenes.length===0||command.makeEntry)?{entrySceneId:command.sceneId}:{})},chapters:replaceAt(project.chapters,chapterAt,nextChapter),scenes:insert(project.scenes,{schemaVersion:1,id:command.sceneId,title:command.title,scriptPath,layoutPath},flatIndex),scripts:{...project.scripts,[command.sceneId]:{schemaVersion:1,sceneId:command.sceneId,statements:[]}},layouts:{...project.layouts,[command.sceneId]:{schemaVersion:1,sceneId:command.sceneId,nodes:[]}}},changed:command.sceneId};}
  const sceneAt="sceneId" in command?project.scenes.findIndex(x=>x.id===command.sceneId):-1;
  if(command.kind.startsWith("scene.")&&sceneAt<0)throw new Error(`scene ${"sceneId" in command?command.sceneId:""} was not found`);
  if(command.kind==="scene.rename")return {project:{...project,scenes:replaceAt(project.scenes,sceneAt,{...project.scenes[sceneAt]!,title:command.title})},changed:command.sceneId};
  if(command.kind==="scene.delete"){const isReferenced=project.manifest.entrySceneId===command.sceneId||references(Object.values(project.scripts).flatMap(script=>script.statements),command.sceneId);let nextProject=project;if(isReferenced){if(command.replacementSceneId===undefined)throw new Error(`referenced entity ${command.sceneId}`);if(command.replacementSceneId===command.sceneId||!project.scenes.some((scene)=>scene.id===command.replacementSceneId))throw new Error(`scene ${command.replacementSceneId} was not found`);nextProject=replaceReferences(project,command.sceneId,command.replacementSceneId) as CanonicalProject;}const path=nextProject.chapters.flatMap(x=>x.scenePaths)[sceneAt]!;const chapterIndex=nextProject.chapters.findIndex(x=>x.scenePaths.includes(path));const scripts={...nextProject.scripts},layouts={...nextProject.layouts};delete scripts[command.sceneId];delete layouts[command.sceneId];return {project:{...nextProject,chapters:replaceAt(nextProject.chapters,chapterIndex,{...nextProject.chapters[chapterIndex]!,scenePaths:nextProject.chapters[chapterIndex]!.scenePaths.filter(x=>x!==path)}),scenes:nextProject.scenes.filter((_,i)=>i!==sceneAt),scripts,layouts},changed:command.sceneId};}
  if(command.kind==="scene.move"){if(chapterAt<0)throw new Error(`chapter ${command.chapterId} was not found`);const paths=project.chapters.flatMap(x=>x.scenePaths);const scenePath=paths[sceneAt]!;let chapters=project.chapters.map(ch=>({...ch,scenePaths:ch.scenePaths.filter(p=>p!==scenePath)}));const target=chapters[chapterAt]!;chapters=replaceAt(chapters,chapterAt,{...target,scenePaths:insert(target.scenePaths,scenePath,command.index)});const order=chapters.flatMap(ch=>ch.scenePaths);const byPath=new Map(paths.map((path,i)=>[path,project.scenes[i]!]));return {project:{...project,chapters,scenes:order.map(path=>byPath.get(path)!)},changed:command.sceneId};}
  if(command.kind==="scene.set-entry")return {project:{...project,manifest:{...project.manifest,entrySceneId:command.sceneId}},changed:command.sceneId};
  if(command.kind.startsWith("statement.")){const sceneId=data.sceneId;if(typeof sceneId!=="string")throw new Error("scene ID is invalid");const statements=project.scripts[sceneId]?.statements;if(!statements)throw new Error(`scene ${sceneId} was not found`);if(command.kind==="statement.insert"){const statement=data.statement;if(statement===null||typeof statement!=="object"||Array.isArray(statement))throw new Error("statement is invalid");const object=statement as JsonObject;const id=entityId(object,"statement");if(hasId(project,id))throw new Error(`duplicate ID ${id}`);const target=typeof data.index==="number"?data.index:undefined;return {project:{...project,scripts:{...project.scripts,[sceneId]:{...project.scripts[sceneId]!,statements:insert(statements,object,target)}}},changed:id};}const statementId=data.statementId;if(typeof statementId!=="string")throw new Error("statement ID is invalid");const at=statements.findIndex(x=>x.id===statementId);if(at<0)throw new Error(`statement ${statementId} was not found`);let next:readonly JsonObject[];if(command.kind==="statement.update"){const patch=data.patch;if(patch===null||typeof patch!=="object"||Array.isArray(patch))throw new Error("statement patch is invalid");next=replaceAt(statements,at,{...statements[at],...(patch as JsonObject),id:statementId});}else if(command.kind==="statement.delete")next=statements.filter((_,i)=>i!==at);else {if(typeof data.index!=="number")throw new Error("index is invalid");next=move(statements,at,data.index);}return {project:{...project,scripts:{...project.scripts,[sceneId]:{...project.scripts[sceneId]!,statements:next}}},changed:statementId};}
  throw new Error("unsupported command");
}

export function createProjectService(project: CanonicalProject): ProjectServiceState { return {project:clone(project),revision:0,appliedCommandIds:new Set(),undoStack:[],redoStack:[]}; }
export function executeProjectBatch(state:ProjectServiceState,commands:readonly ProjectCommand[]):ProjectServiceResult { if(commands.length===0)return fail(state,"batch_empty","INVALID_COMMAND","batch must contain commands");let project=clone(state.project);const changed:string[]=[];const ids=new Set<string>();for(const command of commands){if(state.appliedCommandIds.has(command.commandId)||ids.has(command.commandId))return fail(state,command.commandId,"DUPLICATE_COMMAND","commandId was already applied");if(command.expectedRevision!==state.revision)return fail(state,command.commandId,"STALE_REVISION",`expected ${command.expectedRevision}, current ${state.revision}`);ids.add(command.commandId);try{const result=applyOne(project,command);project=result.project;changed.push(result.changed);}catch(error){const message=error instanceof Error?error.message:String(error);const code:ProjectServiceErrorCode=message.includes("duplicate ID")?"DUPLICATE_ID":message.includes("referenced entity")?"REFERENCE_CONFLICT":message.includes("not found")?"NOT_FOUND":"INVALID_COMMAND";return fail(state,command.commandId,code,message,changed.at(-1));}}
  try{loadProject(saveProject(project));}catch(error){return fail(state,commands.at(-1)!.commandId,"INVALID_PROJECT",error instanceof Error?error.message:String(error));}
  const changeSet:ChangeSet={commandIds:commands.map(x=>x.commandId),baseRevision:state.revision,revision:state.revision+1,beforeHash:semanticHash(state.project),afterHash:semanticHash(project),changedEntityIds:[...new Set(changed)]};const applied=new Set(state.appliedCommandIds);ids.forEach(id=>applied.add(id));return {ok:true,changeSet,state:{project,revision:state.revision+1,appliedCommandIds:applied,undoStack:[...state.undoStack,{project:state.project,changeSet}],redoStack:[],lastChangeSet:changeSet}}; }
export function executeProjectCommand(state:ProjectServiceState,command:ProjectCommand):ProjectServiceResult{return executeProjectBatch(state,[command]);}
export function undoProject(state:ProjectServiceState):ProjectServiceState { const entry=state.undoStack.at(-1);if(!entry)return state;return {...state,project:entry.project,revision:state.revision+1,undoStack:state.undoStack.slice(0,-1),redoStack:[...state.redoStack,{project:state.project,changeSet:entry.changeSet}]}; }
export function redoProject(state:ProjectServiceState):ProjectServiceState { const entry=state.redoStack.at(-1);if(!entry)return state;return {...state,project:entry.project,revision:state.revision+1,undoStack:[...state.undoStack,{project:state.project,changeSet:entry.changeSet}],redoStack:state.redoStack.slice(0,-1)}; }
export function serializeCommittedRevision(state:ProjectServiceState,revision:number):ProjectFiles { if(revision!==state.revision)throw new Error(`STALE_REVISION: expected current revision ${state.revision}`);return saveProject(loadProject(saveProject(state.project))); }
