import { loadProject, loadProjectChapters, loadProjectManifest, loadProjectStructure, PROJECT_MANIFEST_PATH, probeProject, saveProject, semanticHash } from "./codec";
import { exportProjectZip, importProjectZip } from "./project-archive";
import { createStableId } from "./stable-id";
import { sha256 } from "./sha256";
import type { CanonicalProject, ProjectFiles, ProjectStructureIndex } from "./types";

export type ProjectHostKind="windows-directory"|"web-file-system"|"web-opfs"|"web-indexeddb"|"memory-test";
export interface ProjectReference { readonly referenceId:string; readonly hostKind:ProjectHostKind; readonly displayLocation:string; readonly permissionKey:string; }
export interface ProjectSelectedFiles { readonly files:ProjectFiles; readonly version:string; }
export interface ProjectFileStamp { readonly path:string; readonly size:number; readonly modifiedAtMs:number; }
export interface ProjectFileInventory { readonly files:readonly ProjectFileStamp[]; readonly version:string; }
export interface ProjectTrustedSourceFile extends ProjectFileStamp { readonly sha256:string; }
export interface ProjectTrustedSourceCommit { readonly schemaVersion:1; readonly version:string; readonly generation:number; readonly files:readonly ProjectTrustedSourceFile[]; }
export interface ProjectStructureSnapshot { readonly structure:ProjectStructureIndex; readonly files:ProjectFiles; readonly version:string; }
export interface ProjectWorkspace { readonly reference:ProjectReference; readFiles():Promise<{readonly files:ProjectFiles;readonly version:string}>; readSelectedFiles?(paths:readonly string[]):Promise<ProjectSelectedFiles>; listProjectFiles?():Promise<ProjectFileInventory>; readTrustedSourceCommit?():Promise<ProjectTrustedSourceCommit|null>; readDerivedFile?(path:string):Promise<string|null>; writeDerivedFile?(path:string,value:string):Promise<void>; clearDerivedFiles?():Promise<void>; writeFiles(files:ProjectFiles,expectedVersion:string|null):Promise<{readonly version:string}>; }
export interface RecentProject { readonly reference:ProjectReference; readonly projectId:string; readonly title:string; readonly lastOpenedAtMs:number; }
export interface RecentProjectStore { load():Promise<readonly RecentProject[]>; save(items:readonly RecentProject[]):Promise<void>; }
export interface ProjectLifecycleSession { readonly project:CanonicalProject|null; readonly projectId:string; readonly title:string; readonly schemaVersion:number; readonly reference:ProjectReference; readonly hostVersion:string|null; readonly baseHash:string; readonly baseFiles:ProjectFiles; readonly dirty:boolean; readonly recovery:"clean"|"recovered"; readonly access:"editable"|"read-only"; readonly readOnlyReason?:string; }
export type ExternalChangeResult={readonly status:"unchanged";readonly session:ProjectLifecycleSession}|{readonly status:"reloaded";readonly changedPaths:readonly string[];readonly session:ProjectLifecycleSession}|{readonly status:"conflict";readonly changedPaths:readonly string[];readonly baseHash:string;readonly localHash:string;readonly externalHash:string;readonly external:CanonicalProject};
export class ProjectLifecycleError extends Error { constructor(readonly code:"FUTURE_READ_ONLY"|"WRITE_CONFLICT"|"INVALID_TEMPLATE"|"INVALID_PROJECT",message:string){super(message);this.name="ProjectLifecycleError";} }
const SAFE_PROJECT_PATH_SEGMENT=/^[a-z0-9][a-z0-9._-]*$/;
const SHA256_PATTERN=/^[0-9a-f]{64}$/u;
const record=(value:unknown):value is Record<string,unknown>=>value!==null&&!Array.isArray(value)&&typeof value==="object";
export function assertProjectSourcePath(path:string):string{const segments=path.split("/");if(!path.endsWith(".json")||segments.some((segment)=>!SAFE_PROJECT_PATH_SEGMENT.test(segment)||segment==="."||segment==="..")||segments.includes(".world-cache")||segments.includes(".world-host"))throw new Error(`Unsafe project path: ${path}`);return path;}
export function assertSelectedProjectPaths(paths:readonly string[]):readonly string[]{if(paths.length===0||paths.length>256)throw new Error("Selected project read must contain 1 to 256 paths");const seen=new Set<string>();for(const path of paths){assertProjectSourcePath(path);if(seen.has(path))throw new Error(`Duplicate project path: ${path}`);seen.add(path);}return [...paths];}
export function assertDerivedProjectPath(path:string):string{const segments=path.split("/");if(segments.length<2||segments[0]!==".world-cache"||!path.endsWith(".json")||segments.slice(1).some((segment)=>!SAFE_PROJECT_PATH_SEGMENT.test(segment)||segment==="."||segment===".."))throw new Error(`Unsafe derived project path: ${path}`);return path;}
export function isProjectTrustedSourceCommit(value:unknown):value is ProjectTrustedSourceCommit {if(!record(value)||value.schemaVersion!==1||typeof value.version!=="string"||!SHA256_PATTERN.test(value.version)||!Number.isSafeInteger(value.generation)||(value.generation as number)<1||!Array.isArray(value.files))return false;const files:ProjectTrustedSourceFile[]=[];for(const item of value.files){if(!record(item)||typeof item.path!=="string"||typeof item.sha256!=="string"||!SHA256_PATTERN.test(item.sha256)||!Number.isSafeInteger(item.size)||(item.size as number)<0||!Number.isSafeInteger(item.modifiedAtMs)||(item.modifiedAtMs as number)<1)return false;try{assertProjectSourcePath(item.path);}catch{return false;}files.push({path:item.path,size:item.size as number,modifiedAtMs:item.modifiedAtMs as number,sha256:item.sha256});}if(files.some((item,index)=>index>0&&files[index-1]!.path.localeCompare(item.path)>=0))return false;const generation=value.generation as number,payload=JSON.stringify({schemaVersion:1,generation,files:files.map(({path,size,modifiedAtMs,sha256:digest})=>({path,size,modifiedAtMs,sha256:digest}))});return sha256(payload)===value.version;}

export async function readTrustedProjectFiles(workspace:ProjectWorkspace,paths:readonly string[],expectedVersion:string):Promise<ProjectFiles>{
  if(workspace.readSelectedFiles===undefined||workspace.readTrustedSourceCommit===undefined)throw new Error("Trusted selected project read is unsupported");
  const before=await workspace.readTrustedSourceCommit();
  if(before===null||!isProjectTrustedSourceCommit(before)||before.version!==expectedVersion)throw new Error("Project source revision does not match the requested trusted revision");
  const trustedByPath=new Map(before.files.map((entry)=>[entry.path,entry])),files:Record<string,string>={},encoder=new TextEncoder();
  for(let offset=0;offset<paths.length;offset+=256){const batch=paths.slice(offset,offset+256),selected=await workspace.readSelectedFiles(batch);if(selected.version!==expectedVersion)throw new Error("Project source revision changed during trusted selected read");for(const path of batch){const body=selected.files[path],trusted=trustedByPath.get(path);if(body===undefined||trusted===undefined)throw new Error(`Missing project file: ${path}`);if(encoder.encode(body).byteLength!==trusted.size||sha256(body)!==trusted.sha256)throw new Error(`Project source ${path} does not match trusted source commit`);files[path]=body;}}
  const after=await workspace.readTrustedSourceCommit();
  if(after===null||!isProjectTrustedSourceCommit(after)||after.version!==expectedVersion)throw new Error("Project source revision changed during trusted selected read");
  return files;
}

export async function readTrustedProjectStructure(workspace:ProjectWorkspace):Promise<ProjectStructureSnapshot>{if(workspace.readSelectedFiles===undefined||workspace.readTrustedSourceCommit===undefined)throw new Error("Trusted project structure read is unsupported");const before=await workspace.readTrustedSourceCommit();if(before===null||!isProjectTrustedSourceCommit(before))throw new Error("Trusted project source commit is unavailable or invalid");const files:Record<string,string>={},trustedByPath=new Map(before.files.map((entry)=>[entry.path,entry])),encoder=new TextEncoder();const read=async(paths:readonly string[]):Promise<void>=>{for(let offset=0;offset<paths.length;offset+=256){const batch=paths.slice(offset,offset+256),selected=await workspace.readSelectedFiles!(batch);if(selected.version!==before.version)throw new Error("Project source changed while reading project structure");for(const path of batch){const body=selected.files[path],trusted=trustedByPath.get(path);if(body===undefined||trusted===undefined)throw new Error(`Missing project file: ${path}`);if(encoder.encode(body).byteLength!==trusted.size||sha256(body)!==trusted.sha256)throw new Error(`Project source ${path} does not match trusted source commit`);files[path]=body;}}};await read([PROJECT_MANIFEST_PATH]);const manifest=loadProjectManifest(files);await read(manifest.chapterPaths);const chapters=loadProjectChapters(files,manifest);await read(chapters.flatMap((chapter)=>chapter.scenePaths));const structure=loadProjectStructure(files);const after=await workspace.readTrustedSourceCommit();if(after===null||!isProjectTrustedSourceCommit(after)||after.version!==before.version)throw new Error("Project source changed while reading project structure");return {structure,files,version:before.version};}

export function createProjectTemplate(title:string,durableEntropy:string):CanonicalProject {
  if(title.trim()==="")throw new ProjectLifecycleError("INVALID_TEMPLATE","Project title must not be empty");const projectId=createStableId("project",durableEntropy),chapterId=createStableId("chapter",`${durableEntropy}/chapter`),sceneId=createStableId("scene",`${durableEntropy}/scene`),statementId=createStableId("statement",`${durableEntropy}/statement`),chapterPath=`chapters/${chapterId}.json`,scenePath=`scenes/${sceneId}.json`,scriptPath=`scripts/${sceneId}.json`,layoutPath=`layouts/${sceneId}.json`;
  return {mode:"editable",manifest:{schemaVersion:1,fileVersion:"1.0.0",projectId,title:title.trim(),defaultLocale:"und",entrySceneId:sceneId,chapterPaths:[chapterPath],charactersPath:"domain/characters.json",variablesPath:"domain/variables.json",assetsPath:"domain/assets.json",localizationPath:"localization/catalog.json",settingsPath:"settings/project.json",uiPath:"ui/screens.json",pluginsPath:"plugins/plugins.json",testRoutesPath:"tests/routes.json"},chapters:[{schemaVersion:1,id:chapterId,title:"Main",scenePaths:[scenePath]}],scenes:[{schemaVersion:1,id:sceneId,title:"Start",scriptPath,layoutPath}],characters:{schemaVersion:1,characters:[]},variables:{schemaVersion:1,variables:[]},assets:{schemaVersion:1,assets:[]},localization:{schemaVersion:1,locales:[]},settings:{schemaVersion:1,values:{}},ui:{schemaVersion:1,screens:[]},plugins:{schemaVersion:1,plugins:[]},testRoutes:{schemaVersion:1,routes:[]},scripts:{[sceneId]:{schemaVersion:1,sceneId,statements:[{id:statementId,kind:"end",endingName:"Ending"}]}},layouts:{[sceneId]:{schemaVersion:1,sceneId,nodes:[]}}};
}
export async function rememberRecent(store:RecentProjectStore,session:ProjectLifecycleSession,nowMs:number):Promise<void>{const current=await store.load();const item:RecentProject={reference:session.reference,projectId:session.projectId,title:session.title,lastOpenedAtMs:nowMs};await store.save([item,...current.filter(value=>value.reference.referenceId!==session.reference.referenceId)].slice(0,20));}
export async function createProject(workspace:ProjectWorkspace,title:string,durableEntropy:string):Promise<ProjectLifecycleSession>{const project=createProjectTemplate(title,durableEntropy),baseFiles=saveProject(project);const result=await workspace.writeFiles(baseFiles,null);return {project,projectId:project.manifest.projectId,title:project.manifest.title,schemaVersion:1,reference:workspace.reference,hostVersion:result.version,baseHash:semanticHash(project),baseFiles,dirty:false,recovery:"clean",access:"editable"};}
export async function openProject(workspace:ProjectWorkspace):Promise<ProjectLifecycleSession>{const snapshot=await workspace.readFiles();const probe=probeProject(snapshot.files);if(probe.status==="future-read-only")return {project:null,projectId:probe.projectId??"unknown_project",title:probe.title??"Future Project",schemaVersion:probe.schemaVersion,reference:workspace.reference,hostVersion:snapshot.version,baseHash:"",baseFiles:snapshot.files,dirty:false,recovery:"clean",access:"read-only",readOnlyReason:`Project schema ${probe.schemaVersion} requires a newer editor`};const project=loadProject(snapshot.files);return {project,projectId:project.manifest.projectId,title:project.manifest.title,schemaVersion:1,reference:workspace.reference,hostVersion:snapshot.version,baseHash:semanticHash(project),baseFiles:snapshot.files,dirty:false,recovery:"clean",access:"editable"};}
export function markProjectDirty(session:ProjectLifecycleSession,project:CanonicalProject):ProjectLifecycleSession{return {...session,project,projectId:project.manifest.projectId,title:project.manifest.title,dirty:semanticHash(project)!==session.baseHash};}
export async function saveLifecycleProject(workspace:ProjectWorkspace,session:ProjectLifecycleSession):Promise<ProjectLifecycleSession>{if(session.access!=="editable"||session.project===null)throw new ProjectLifecycleError("FUTURE_READ_ONLY",session.readOnlyReason??"Project is read-only");try{const baseFiles=saveProject(session.project),result=await workspace.writeFiles(baseFiles,session.hostVersion);const hash=semanticHash(session.project);return {...session,hostVersion:result.version,baseHash:hash,baseFiles,dirty:false};}catch(error){throw new ProjectLifecycleError("WRITE_CONFLICT",error instanceof Error?error.message:String(error));}}
export function exportLifecycleProject(session:ProjectLifecycleSession):Uint8Array{if(session.project===null)throw new ProjectLifecycleError("FUTURE_READ_ONLY","Read-only future projects cannot be exported through the current codec");return exportProjectZip(saveProject(session.project));}
export function importLifecycleProject(archive:Uint8Array):CanonicalProject{return loadProject(importProjectZip(archive));}
function changedPaths(base:ProjectFiles,next:ProjectFiles):readonly string[]{return [...new Set([...Object.keys(base),...Object.keys(next)])].filter((path)=>base[path]!==next[path]).sort();}
export async function detectExternalChange(workspace:ProjectWorkspace,session:ProjectLifecycleSession):Promise<ExternalChangeResult>{if(session.project===null)return {status:"unchanged",session};const snapshot=await workspace.readFiles(),external=loadProject(snapshot.files),externalHash=semanticHash(external),localHash=semanticHash(session.project),paths=changedPaths(session.baseFiles,snapshot.files);if(externalHash===session.baseHash)return {status:"unchanged",session};if(!session.dirty||localHash===session.baseHash)return {status:"reloaded",changedPaths:paths,session:{...session,project:external,projectId:external.manifest.projectId,title:external.manifest.title,hostVersion:snapshot.version,baseHash:externalHash,baseFiles:snapshot.files,dirty:false}};return {status:"conflict",changedPaths:paths,baseHash:session.baseHash,localHash,externalHash,external};}
