import type { ProjectFiles } from "./types";

export type ProjectArchiveBinaryFiles = Readonly<Record<string, Uint8Array>>;
export interface ProjectArchiveLimits { readonly maxEntries:number; readonly maxEntryBytes:number; readonly maxTotalBytes:number; }

export class ProjectArchiveError extends Error {
  constructor(readonly code: "INVALID_ARCHIVE" | "UNSAFE_PATH" | "DUPLICATE_PATH" | "SIZE_LIMIT" | "UNSUPPORTED_COMPRESSION", message: string) { super(message); this.name="ProjectArchiveError"; }
}
const encoder=new TextEncoder(),decoder=new TextDecoder("utf-8",{fatal:true});
const table=Array.from({length:256},(_,n)=>{let value=n;for(let i=0;i<8;i+=1)value=(value&1)!==0?0xedb88320^(value>>>1):value>>>1;return value>>>0;});
function crc32(bytes:Uint8Array):number{let crc=0xffffffff;for(const byte of bytes)crc=(table[(crc^byte)&0xff]??0)^(crc>>>8);return (crc^0xffffffff)>>>0;}
function safe(path:string):void{if(path.length===0||path.length>240||path.startsWith("/")||path.includes("\\")||path.includes("\0")||/^[A-Za-z]:/.test(path)||path.split("/").some(part=>part===""||part==="."||part===".."))throw new ProjectArchiveError("UNSAFE_PATH",`Unsafe archive path: ${path}`);}
function u16(view:DataView,offset:number,value:number){view.setUint16(offset,value,true);}function u32(view:DataView,offset:number,value:number){view.setUint32(offset,value,true);}
function concat(parts:readonly Uint8Array[]):Uint8Array{const out=new Uint8Array(parts.reduce((sum,item)=>sum+item.length,0));let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length;}return out;}

/** Deterministic ZIP32 writer using stored entries, so no platform compression API enters project-domain. */
export function exportProjectBinaryZip(files:ProjectArchiveBinaryFiles):Uint8Array {
  const locals:Uint8Array[]=[],centrals:Uint8Array[]=[];let offset=0;
  for(const [path,source] of Object.entries(files).sort(([a],[b])=>a.localeCompare(b))){safe(path);const name=encoder.encode(path),data=source.slice(),crc=crc32(data);const local=new Uint8Array(30+name.length);const lv=new DataView(local.buffer);u32(lv,0,0x04034b50);u16(lv,4,20);u16(lv,6,0x0800);u16(lv,8,0);u32(lv,14,crc);u32(lv,18,data.length);u32(lv,22,data.length);u16(lv,26,name.length);local.set(name,30);locals.push(local,data);const central=new Uint8Array(46+name.length);const cv=new DataView(central.buffer);u32(cv,0,0x02014b50);u16(cv,4,20);u16(cv,6,20);u16(cv,8,0x0800);u16(cv,10,0);u32(cv,16,crc);u32(cv,20,data.length);u32(cv,24,data.length);u16(cv,28,name.length);u32(cv,42,offset);central.set(name,46);centrals.push(central);offset+=local.length+data.length;}
  const central=concat(centrals);const end=new Uint8Array(22);const ev=new DataView(end.buffer);u32(ev,0,0x06054b50);u16(ev,8,centrals.length);u16(ev,10,centrals.length);u32(ev,12,central.length);u32(ev,16,offset);return concat([...locals,central,end]);
}

export function importProjectBinaryZip(archive:Uint8Array,limits:ProjectArchiveLimits={maxEntries:2048,maxEntryBytes:16*1024*1024,maxTotalBytes:128*1024*1024}):Record<string,Uint8Array> {
  if(archive.length<22)throw new ProjectArchiveError("INVALID_ARCHIVE","ZIP is truncated");let end=-1;for(let i=archive.length-22;i>=Math.max(0,archive.length-65557);i-=1){if(new DataView(archive.buffer,archive.byteOffset+i,4).getUint32(0,true)===0x06054b50){end=i;break;}}if(end<0)throw new ProjectArchiveError("INVALID_ARCHIVE","ZIP end record is missing");const ev=new DataView(archive.buffer,archive.byteOffset+end,22);const count=ev.getUint16(10,true),centralOffset=ev.getUint32(16,true);if(count>limits.maxEntries)throw new ProjectArchiveError("SIZE_LIMIT","ZIP has too many entries");const files:Record<string,Uint8Array>={};let cursor=centralOffset,total=0;
  for(let entry=0;entry<count;entry+=1){if(cursor+46>archive.length)throw new ProjectArchiveError("INVALID_ARCHIVE","Central directory is truncated");const cv=new DataView(archive.buffer,archive.byteOffset+cursor,46);if(cv.getUint32(0,true)!==0x02014b50)throw new ProjectArchiveError("INVALID_ARCHIVE","Central directory signature is invalid");const method=cv.getUint16(10,true),crc=cv.getUint32(16,true),compressed=cv.getUint32(20,true),size=cv.getUint32(24,true),nameLength=cv.getUint16(28,true),extra=cv.getUint16(30,true),comment=cv.getUint16(32,true),localOffset=cv.getUint32(42,true);if(method!==0)throw new ProjectArchiveError("UNSUPPORTED_COMPRESSION","Only stored ZIP entries are accepted");if(size!==compressed||size>limits.maxEntryBytes||total+size>limits.maxTotalBytes)throw new ProjectArchiveError("SIZE_LIMIT","ZIP entry exceeds the import budget");let path:string;try{path=decoder.decode(archive.subarray(cursor+46,cursor+46+nameLength));}catch{throw new ProjectArchiveError("INVALID_ARCHIVE","ZIP path is not valid UTF-8");}safe(path);if(path in files)throw new ProjectArchiveError("DUPLICATE_PATH",`Duplicate archive path: ${path}`);if(localOffset+30>archive.length)throw new ProjectArchiveError("INVALID_ARCHIVE","Local entry is truncated");const lv=new DataView(archive.buffer,archive.byteOffset+localOffset,30);if(lv.getUint32(0,true)!==0x04034b50)throw new ProjectArchiveError("INVALID_ARCHIVE","Local entry signature is invalid");const localName=lv.getUint16(26,true),localExtra=lv.getUint16(28,true),start=localOffset+30+localName+localExtra,endData=start+size;if(endData>archive.length)throw new ProjectArchiveError("INVALID_ARCHIVE","Entry payload is truncated");const data=archive.subarray(start,endData);if(crc32(data)!==crc)throw new ProjectArchiveError("INVALID_ARCHIVE",`CRC mismatch: ${path}`);files[path]=data.slice();total+=size;cursor+=46+nameLength+extra+comment;}
  return files;
}

export function exportProjectZip(files:ProjectFiles):Uint8Array{return exportProjectBinaryZip(Object.fromEntries(Object.entries(files).map(([path,source])=>[path,encoder.encode(source)])));}
export function importProjectZip(archive:Uint8Array,limits?:ProjectArchiveLimits):ProjectFiles{const binary=importProjectBinaryZip(archive,limits),files:Record<string,string>={};for(const [path,data] of Object.entries(binary)){try{files[path]=decoder.decode(data);}catch{throw new ProjectArchiveError("INVALID_ARCHIVE",`${path} is not UTF-8 text`);}}return files;}
