import { describe,expect,it } from "vitest";
import { BrowserDirectoryProjectWorkspace } from "./browser-project-workspace";
class FileHandle {readonly kind="file" as const;readonly reads={value:0};readonly modified={value:1};constructor(readonly data:{value:string}){}async getFile(){return {size:this.data.value.length,lastModified:this.modified.value,text:async()=>{this.reads.value++;return this.data.value;}};}async createWritable(){return {write:async(value:string)=>{this.data.value=value;this.modified.value++;},close:async()=>undefined};}}
class DirectoryHandle {readonly kind="directory" as const;readonly children=new Map<string,FileHandle|DirectoryHandle>();constructor(readonly name:string){}async *entries():AsyncIterableIterator<[string,FileHandle|DirectoryHandle]>{yield* this.children.entries();}async getDirectoryHandle(name:string,options?:{create?:boolean}){const item=this.children.get(name);if(item instanceof DirectoryHandle)return item;if(!options?.create)throw new Error("missing directory");const created=new DirectoryHandle(name);this.children.set(name,created);return created;}async getFileHandle(name:string,options?:{create?:boolean}){const item=this.children.get(name);if(item instanceof FileHandle)return item;if(!options?.create)throw new Error("missing file");const created=new FileHandle({value:""});this.children.set(name,created);return created;}async removeEntry(name:string){this.children.delete(name);}}
describe("Browser directory project workspace",()=>{it("writes nested canonical files and detects external changes",async()=>{const root=new DirectoryHandle("Story");const workspace=new BrowserDirectoryProjectWorkspace(root,"story");const first=await workspace.writeFiles({"world.project.json":"{\"schemaVersion\":1}","scripts/scene.json":"{}"},null);expect((await workspace.readFiles()).files["scripts/scene.json"]).toBe("{}");(await root.getFileHandle("world.project.json")).data.value="external";await expect(workspace.writeFiles({"world.project.json":"next"},first.version)).rejects.toThrow(/External project version changed/);});});

it("reads only explicitly requested canonical files for a future lazy Route window",async()=>{const root=new DirectoryHandle("Story");const workspace=new BrowserDirectoryProjectWorkspace(root,"story");await workspace.writeFiles({"world.project.json":"manifest","scripts/scene_a.json":"a","scripts/scene_b.json":"b"},null);const manifest=await root.getFileHandle("world.project.json"),sceneA=await (await root.getDirectoryHandle("scripts")).getFileHandle("scene_a.json"),sceneB=await (await root.getDirectoryHandle("scripts")).getFileHandle("scene_b.json");manifest.reads.value=0;sceneA.reads.value=0;sceneB.reads.value=0;await expect(workspace.readSelectedFiles(["world.project.json","scripts/scene_b.json"])).resolves.toMatchObject({files:{"world.project.json":"manifest","scripts/scene_b.json":"b"}});expect([manifest.reads.value,sceneA.reads.value,sceneB.reads.value]).toEqual([1,0,1]);await expect(workspace.readSelectedFiles(["../secret.json"])).rejects.toThrow(/Unsafe project path/);});

it("lists source JSON stamps without reading file bodies and changes the inventory version on metadata changes",async()=>{const root=new DirectoryHandle("Story");const workspace=new BrowserDirectoryProjectWorkspace(root,"story");await workspace.writeFiles({"world.project.json":"manifest","scripts/scene_a.json":"alpha","scripts/scene_b.json":"beta"},null);const manifest=await root.getFileHandle("world.project.json"),sceneA=await (await root.getDirectoryHandle("scripts")).getFileHandle("scene_a.json"),sceneB=await (await root.getDirectoryHandle("scripts")).getFileHandle("scene_b.json");manifest.reads.value=0;sceneA.reads.value=0;sceneB.reads.value=0;await root.getDirectoryHandle(".world-cache",{create:true});const listed=await workspace.listProjectFiles();expect(listed.files.map((item)=>item.path)).toEqual(["scripts/scene_a.json","scripts/scene_b.json","world.project.json"]);expect(listed.files).toContainEqual({path:"scripts/scene_a.json",size:5,modifiedAtMs:2});expect([manifest.reads.value,sceneA.reads.value,sceneB.reads.value]).toEqual([0,0,0]);sceneA.data.value="changed";sceneA.modified.value++;const changed=await workspace.listProjectFiles();expect(changed.version).not.toBe(listed.version);expect([manifest.reads.value,sceneA.reads.value,sceneB.reads.value]).toEqual([0,0,0]);});

it("isolates disposable cache files and invalidates them before source writes",async()=>{const root=new DirectoryHandle("Story");const workspace=new BrowserDirectoryProjectWorkspace(root,"story");const first=await workspace.writeFiles({"world.project.json":"manifest"},null);await workspace.writeDerivedFile(".world-cache/compiler-v1.json","cached");await expect(workspace.readDerivedFile(".world-cache/compiler-v1.json")).resolves.toBe("cached");expect((await workspace.readFiles()).files).toEqual({"world.project.json":"manifest"});await workspace.writeFiles({"world.project.json":"changed"},first.version);await expect(workspace.readDerivedFile(".world-cache/compiler-v1.json")).resolves.toBeNull();await expect(workspace.writeDerivedFile(".world-cache/../secret.json","bad")).rejects.toThrow(/Unsafe derived project path/);});
