import { assertSelectedProjectPaths, type ProjectFiles, type ProjectFileStamp, type ProjectReference, type ProjectWorkspace } from "@world-studio/project-domain";

export interface BrowserFileHandle { readonly kind:"file"; getFile():Promise<{readonly size:number;readonly lastModified:number;text():Promise<string>}>; createWritable():Promise<{write(value:string):Promise<void>;close():Promise<void>}>; }
export interface BrowserDirectoryHandle { readonly kind:"directory"; readonly name:string; entries():AsyncIterableIterator<[string,BrowserFileHandle|BrowserDirectoryHandle]>; getDirectoryHandle(name:string,options?:{create?:boolean}):Promise<BrowserDirectoryHandle>; getFileHandle(name:string,options?:{create?:boolean}):Promise<BrowserFileHandle>; removeEntry(name:string,options?:{recursive?:boolean}):Promise<void>; }
const SAFE_SEGMENT=/^[a-z0-9._-]+$/;
function version(files:ProjectFiles):string{let hash=2166136261;for(const [path,value] of Object.entries(files).sort(([a],[b])=>a.localeCompare(b))){for(const code of `${path}\0${value}\0`)hash=Math.imul(hash^code.charCodeAt(0),16777619);}return (hash>>>0).toString(16).padStart(8,"0");}
async function scan(directory:BrowserDirectoryHandle,prefix=""):Promise<Record<string,string>>{const files:Record<string,string>={};for await(const [name,handle] of directory.entries()){if(!SAFE_SEGMENT.test(name)||name===".world-cache"||name===".world-host")continue;const path=prefix?`${prefix}/${name}`:name;if(handle.kind==="directory")Object.assign(files,await scan(handle,path));else if(name.endsWith(".json"))files[path]=await (await handle.getFile()).text();}return files;}
async function inventory(directory:BrowserDirectoryHandle,prefix=""):Promise<ProjectFileStamp[]>{const files:ProjectFileStamp[]=[];for await(const [name,handle] of directory.entries()){if(!SAFE_SEGMENT.test(name)||name===".world-cache"||name===".world-host")continue;const path=prefix?`${prefix}/${name}`:name;if(handle.kind==="directory")files.push(...await inventory(handle,path));else if(name.endsWith(".json")){const file=await handle.getFile();if(!Number.isSafeInteger(file.size)||file.size<0||!Number.isSafeInteger(file.lastModified)||file.lastModified<0)throw new Error(`Project file metadata is unavailable: ${path}`);files.push({path,size:file.size,modifiedAtMs:file.lastModified});}}return files.sort((left,right)=>left.path.localeCompare(right.path));}
async function parent(root:BrowserDirectoryHandle,path:string,create=true):Promise<{directory:BrowserDirectoryHandle;name:string}>{const parts=path.split("/");const name=parts.pop();if(name===undefined)throw new Error("invalid project path");let directory=root;for(const part of parts)directory=await directory.getDirectoryHandle(part,{create});return {directory,name};}
export class BrowserDirectoryProjectWorkspace implements ProjectWorkspace {
  readonly reference:ProjectReference;
  constructor(readonly directoryHandle:BrowserDirectoryHandle,referenceId:string,hostKind:"web-file-system"|"web-opfs"="web-file-system"){this.reference={referenceId,hostKind,displayLocation:directoryHandle.name,permissionKey:`directory:${referenceId}`};}
  async readFiles(){const files=await scan(this.directoryHandle);return {files,version:version(files)};}
  async readSelectedFiles(paths:readonly string[]){const files:Record<string,string>={};for(const path of assertSelectedProjectPaths(paths)){const target=await parent(this.directoryHandle,path,false);let handle:BrowserFileHandle;try{handle=await target.directory.getFileHandle(target.name);}catch{throw new Error(`Missing project file: ${path}`);}files[path]=await (await handle.getFile()).text();}return {files,version:version(files)};}
  async listProjectFiles(){const files=await inventory(this.directoryHandle);return {files,version:version(Object.fromEntries(files.map((item)=>[item.path,`${item.size}:${item.modifiedAtMs}`])))};}
  async writeFiles(files:ProjectFiles,expectedVersion:string|null){const current=await this.readFiles();if(expectedVersion!==null&&current.version!==expectedVersion)throw new Error(`External project version changed from ${expectedVersion} to ${current.version}`);for(const path of Object.keys(current.files).filter((path)=>files[path]===undefined)){const target=await parent(this.directoryHandle,path,false);await target.directory.removeEntry(target.name);}for(const [path,value] of Object.entries(files)){const target=await parent(this.directoryHandle,path);const writable=await (await target.directory.getFileHandle(target.name,{create:true})).createWritable();await writable.write(value);await writable.close();}const written=await this.readFiles();return {version:written.version};}
}
export interface BrowserProjectPicker { showDirectoryPicker?:()=>Promise<BrowserDirectoryHandle>; navigator?:{storage?:{getDirectory():Promise<BrowserDirectoryHandle>}}; }
export async function pickBrowserDirectoryWorkspace(browser:BrowserProjectPicker,referenceId:string):Promise<BrowserDirectoryProjectWorkspace>{if(browser.showDirectoryPicker===undefined)throw new Error("File System Access API is unavailable");return new BrowserDirectoryProjectWorkspace(await browser.showDirectoryPicker(),referenceId);}
export async function createOpfsProjectWorkspace(browser:BrowserProjectPicker,projectFolder:string):Promise<BrowserDirectoryProjectWorkspace>{const root=await browser.navigator?.storage?.getDirectory();if(root===undefined)throw new Error("OPFS is unavailable");const projects=await root.getDirectoryHandle("world-projects",{create:true});const directory=await projects.getDirectoryHandle(projectFolder,{create:true});return new BrowserDirectoryProjectWorkspace(directory,`opfs_${projectFolder}`,"web-opfs");}
