import { fireEvent, render, screen } from "@testing-library/react";
import { createCharacterEntity, createProject, createProjectService, createProjectTemplate, executeProjectBatch, openProject, saveProject, type ProjectCommand, type ProjectFiles, type ProjectLifecycleSession, type ProjectReference, type ProjectWorkspace } from "@world-studio/project-domain";
import { describe, expect, it, vi } from "vitest";
import { ProjectEntityManager } from "./project-entity-manager";

class MemoryWorkspace implements ProjectWorkspace { readonly reference:ProjectReference={referenceId:"n13",hostKind:"memory-test",displayLocation:"Memory/N13",permissionKey:"n13"};files:ProjectFiles={};version=0;async readFiles(){return {files:this.files,version:String(this.version)};}async writeFiles(files:ProjectFiles,expectedVersion:string|null){if(expectedVersion!==null&&expectedVersion!==String(this.version))throw new Error("stale");this.files=structuredClone(files);this.version++;return {version:String(this.version)};}}
const set=(label:string,value:string)=>fireEvent.change(screen.getByLabelText(label),{target:{value}});
describe("ProjectEntityManager",()=>{
  it("builds the N13 acceptance skeleton, saves it, and reopens with stable references",async()=>{
    const workspace=new MemoryWorkspace();const session=await createProject(workspace,"N13 Story","018f08d8-71a1-7bc2-a627-2f4a843ee190");let next=0;const onSession=vi.fn();render(<ProjectEntityManager session={session} workspace={workspace} onSession={onSession} onOpenEditor={()=>undefined} idFactory={()=>`id${++next}`}/>);
    set("新场景名称","Middle");fireEvent.click(screen.getByRole("button",{name:"新增场景"}));set("新场景名称","Ending");fireEvent.click(screen.getByRole("button",{name:"新增场景"}));
    set("角色显示名","Aya");set("角色颜色","#ff44aa");set("立绘槽位","main,closeup");set("默认表情","neutral");fireEvent.click(screen.getByRole("button",{name:"新增角色"}));set("角色显示名","Ren");set("角色颜色","#4488ff");set("立绘槽位","main");set("默认表情","smile");fireEvent.click(screen.getByRole("button",{name:"新增角色"}));
    set("变量名称","Flag");set("变量默认值","false");fireEvent.click(screen.getByRole("button",{name:"新增变量"}));set("变量名称","Trust");set("变量类型","number");set("变量默认值","3");fireEvent.click(screen.getByRole("button",{name:"新增变量"}));set("变量名称","Route");set("变量类型","string");set("变量默认值","common");fireEvent.click(screen.getByRole("button",{name:"新增变量"}));
    fireEvent.click(screen.getAllByRole("button",{name:"设为入口"}).at(-1)!);fireEvent.click(screen.getByRole("button",{name:"保存工程"}));await screen.findByText("已保存到工程目录");const reopened=await openProject(workspace);expect(reopened.project?.scenes).toHaveLength(3);expect(reopened.project?.characters.characters).toHaveLength(2);expect(reopened.project?.variables.variables).toHaveLength(3);expect(reopened.project?.characters.characters[0]).toMatchObject({displayName:"Aya",portraitSlots:["main","closeup"],defaultExpression:"neutral"});expect(reopened.project?.variables.variables.map((item)=>item.type)).toEqual(["boolean","number","string"]);expect(reopened.project?.scenes.slice(1).map((scene)=>reopened.project?.scripts[scene.id]?.statements)).toMatchObject([[{kind:"end",endingName:"未命名结局"}],[{kind:"end",endingName:"未命名结局"}]]);const saved=onSession.mock.calls[0]?.[0] as ProjectLifecycleSession;expect(reopened.project?.scenes.map((item)=>item.id)).toEqual(saved.project?.scenes.map((item)=>item.id));expect(reopened.project?.manifest.entrySceneId).toBe(saved.project?.manifest.entrySceneId);
  });
  it("searches all managed entities and exposes button-based ordering",async()=>{
    const workspace=new MemoryWorkspace();const session=await createProject(workspace,"Search Story","018f08d8-71a1-7bc2-a627-2f4a843ee191");render(<ProjectEntityManager session={session} workspace={workspace} onSession={()=>undefined} onOpenEditor={()=>undefined} idFactory={()=>"searchid"}/>);set("搜索全部实体","Main");expect(screen.getByRole("list",{name:"搜索结果"})).toHaveTextContent("章节");expect(screen.getByRole("button",{name:/Main上移/})).toBeDisabled();expect(screen.getByRole("button",{name:/Start上移/})).toBeDisabled();
  });
  it("shows reference locations and migrates them before deletion",async()=>{
    const workspace=new MemoryWorkspace();let service=createProjectService(createProjectTemplate("Migration UI","018f08d8-71a1-7bc2-a627-2f4a843ee192"));const sceneId=service.project.manifest.entrySceneId;const commands=[{commandId:"command_a",expectedRevision:0,kind:"character.create",character:createCharacterEntity("character_a","A","#112233",["main"],"neutral")},{commandId:"command_b",expectedRevision:0,kind:"character.create",character:createCharacterEntity("character_b","B","#445566",["main"],"neutral")},{commandId:"command_line",expectedRevision:0,kind:"statement.insert",sceneId,statement:{id:"statement_line",kind:"dialogue",speakerId:"character_a",textId:"text_line",text:"Hello"}}] as ProjectCommand[];const built=executeProjectBatch(service,commands);expect(built.ok).toBe(true);if(!built.ok)return;service=built.state;await workspace.writeFiles(saveProject(service.project),null);const session=await openProject(workspace);let next=0;render(<ProjectEntityManager session={session} workspace={workspace} onSession={()=>undefined} onOpenEditor={()=>undefined} idFactory={()=>`migrate${++next}`}/>);
    fireEvent.click(screen.getByRole("button",{name:"删除角色A"}));expect(screen.getByRole("alertdialog",{name:"删除前引用分析"})).toHaveTextContent("speakerId");set("替代实体","character_b");fireEvent.click(screen.getByRole("button",{name:"迁移引用并删除"}));fireEvent.click(screen.getByRole("button",{name:"保存工程"}));await screen.findByText("已保存到工程目录");const reopened=await openProject(workspace);expect(reopened.project?.characters.characters.map((item)=>item.id)).toEqual(["character_b"]);expect(reopened.project?.scripts[sceneId]?.statements.at(-1)).toMatchObject({speakerId:"character_b"});
  });
});
