import { useMemo, useState, type FormEvent } from "react";
import { analyzeProjectEntityReferences, createCharacterEntity, createProjectService, createVariableEntity, executeProjectCommand, markProjectDirty, redoProject, saveLifecycleProject, searchProjectEntities, undoProject, type ProjectCommand, type ProjectLifecycleSession, type ProjectWorkspace, type VariableScope, type VariableType } from "@world-studio/project-domain";

type EntityKind="chapter"|"scene"|"character"|"variable";
interface PendingDelete { readonly kind:EntityKind;readonly id:string;readonly references:ReturnType<typeof analyzeProjectEntityReferences>; }
const field=(form:FormData,name:string)=>String(form.get(name)??"").trim();
const defaultId=()=>crypto.randomUUID().replaceAll("-","").slice(0,16);

export function ProjectEntityManager({session,workspace,onSession,onOpenEditor,idFactory=defaultId}:{readonly session:ProjectLifecycleSession;readonly workspace:ProjectWorkspace;readonly onSession:(session:ProjectLifecycleSession)=>void;readonly onOpenEditor:(project:NonNullable<ProjectLifecycleSession["project"]>)=>void;readonly idFactory?:()=>string}){
  const [service,setService]=useState(()=>createProjectService(session.project!));const [query,setQuery]=useState("");const [message,setMessage]=useState("已同步");const [pendingDelete,setPendingDelete]=useState<PendingDelete|null>(null);const [replacement,setReplacement]=useState("");
  const project=service.project,results=useMemo(()=>searchProjectEntities(project,query),[project,query]);
  const run=(value:Omit<ProjectCommand,"commandId"|"expectedRevision">|Record<string,unknown>)=>{const result=executeProjectCommand(service,{commandId:`command_${idFactory()}`,expectedRevision:service.revision,...value} as ProjectCommand);if(!result.ok){setMessage(`${result.error.code}：${result.error.message}`);return false;}setService(result.state);setMessage(`有未保存修改 · revision ${result.state.revision}`);return true;};
  const submit=(event:FormEvent<HTMLFormElement>,action:(data:FormData)=>void)=>{event.preventDefault();try{action(new FormData(event.currentTarget));event.currentTarget.reset();}catch(reason){setMessage(reason instanceof Error?reason.message:String(reason));}};
  const requestDelete=(kind:EntityKind,id:string)=>{const references=analyzeProjectEntityReferences(project,id);if(references.length===0){run({kind:`${kind}.delete`,[`${kind}Id`]:id});return;}setReplacement("");setPendingDelete({kind,id,references});};
  const confirmDelete=()=>{if(!pendingDelete)return;const replacementField=pendingDelete.kind==="scene"?"replacementSceneId":pendingDelete.kind==="character"?"replacementCharacterId":pendingDelete.kind==="variable"?"replacementVariableId":undefined;if(replacementField===undefined){setMessage("章节仍包含场景，需先移动或删除场景");return;}if(run({kind:`${pendingDelete.kind}.delete`,[`${pendingDelete.kind}Id`]:pendingDelete.id,[replacementField]:replacement})){setPendingDelete(null);setReplacement("");}};
  const save=async()=>{setMessage("正在保存…");try{const saved=await saveLifecycleProject(workspace,markProjectDirty(session,service.project));onSession(saved);setMessage("已保存到工程目录");}catch(reason){setMessage(reason instanceof Error?reason.message:String(reason));}};
  const moveScene=(sceneId:string,delta:number)=>{const scenePath=`scenes/${sceneId}.json`;const chapter=project.chapters.find((item)=>item.scenePaths.includes(scenePath));if(!chapter)return;const at=chapter.scenePaths.indexOf(scenePath);run({kind:"scene.move",sceneId,chapterId:chapter.id,index:Math.max(0,Math.min(chapter.scenePaths.length-1,at+delta))});};
  return <main className="entity-manager" aria-label="项目结构管理">
    <header className="entity-manager__header"><div><p className="eyebrow">PROJECT STRUCTURE</p><h1>{project.manifest.title}</h1><p>{session.reference.displayLocation}</p></div><div className="project-home__actions"><button onClick={()=>{setService(undoProject(service));setMessage("已撤销，尚未保存");}} disabled={service.undoStack.length===0}>撤销</button><button onClick={()=>{setService(redoProject(service));setMessage("已重做，尚未保存");}} disabled={service.redoStack.length===0}>重做</button><button onClick={()=>void save()}>保存工程</button><button onClick={()=>onOpenEditor(project)}>进入内容编辑器</button></div></header>
    <p role="status">{message}</p>
    <section className="entity-manager__search"><label>搜索全部实体<input aria-label="搜索全部实体" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="名称、稳定 ID、类型或作用域" /></label>{query?<ul aria-label="搜索结果">{results.map((item)=><li key={`${item.kind}:${item.id}`}><strong>{item.label}</strong><span>{item.detail}</span><code>{item.id}</code></li>)}</ul>:null}</section>
    <div className="entity-manager__grid">
      <section className="entity-manager__card" aria-labelledby="chapters-heading"><h2 id="chapters-heading">章节与场景</h2>
        <form onSubmit={(event)=>submit(event,(data)=>run({kind:"chapter.create",chapterId:`chapter_${idFactory()}`,title:field(data,"title")}))}><input name="title" aria-label="新章节名称" required placeholder="章节名称"/><button>新增章节</button></form>
        <form onSubmit={(event)=>submit(event,(data)=>run({kind:"scene.create",chapterId:field(data,"chapterId"),sceneId:`scene_${idFactory()}`,title:field(data,"title")}))}><select name="chapterId" aria-label="新场景所属章节">{project.chapters.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><input name="title" aria-label="新场景名称" required placeholder="场景名称"/><button>新增场景</button></form>
        <ol>{project.chapters.map((chapter,chapterIndex)=><li key={chapter.id}><form className="entity-row" onSubmit={(event)=>submit(event,(data)=>run({kind:"chapter.rename",chapterId:chapter.id,title:field(data,"title")}))}><input name="title" aria-label={`${chapter.title}章节名称`} defaultValue={chapter.title}/><code>{chapter.id}</code><button>保存名称</button><button type="button" aria-label={`${chapter.title}上移`} disabled={chapterIndex===0} onClick={()=>run({kind:"chapter.move",chapterId:chapter.id,index:chapterIndex-1})}>↑</button><button type="button" aria-label={`${chapter.title}下移`} disabled={chapterIndex===project.chapters.length-1} onClick={()=>run({kind:"chapter.move",chapterId:chapter.id,index:chapterIndex+1})}>↓</button><button type="button" aria-label={`删除章节${chapter.title}`} onClick={()=>requestDelete("chapter",chapter.id)}>删除</button></form><ol>{chapter.scenePaths.map((path,index)=>{const scene=project.scenes.find((item)=>item.id===path.slice(7,-5));if(!scene)return null;return <li key={scene.id}><form className="entity-row entity-row--scene" onSubmit={(event)=>submit(event,(data)=>run({kind:"scene.rename",sceneId:scene.id,title:field(data,"title")}))}><input name="title" aria-label={`${scene.title}场景名称`} defaultValue={scene.title}/><code>{scene.id}</code><select aria-label={`${scene.title}所属章节`} value={chapter.id} onChange={(event)=>run({kind:"scene.move",sceneId:scene.id,chapterId:event.target.value,index:project.chapters.find((item)=>item.id===event.target.value)?.scenePaths.length??0})}>{project.chapters.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select>{project.manifest.entrySceneId===scene.id?<span>入口</span>:<button type="button" onClick={()=>run({kind:"scene.set-entry",sceneId:scene.id})}>设为入口</button>}<button>保存名称</button><button type="button" aria-label={`${scene.title}上移`} disabled={index===0} onClick={()=>moveScene(scene.id,-1)}>↑</button><button type="button" aria-label={`${scene.title}下移`} disabled={index===chapter.scenePaths.length-1} onClick={()=>moveScene(scene.id,1)}>↓</button><button type="button" aria-label={`删除场景${scene.title}`} onClick={()=>requestDelete("scene",scene.id)}>删除</button></form></li>;})}</ol></li>)}</ol>
      </section>
      <section className="entity-manager__card" aria-labelledby="characters-heading"><h2 id="characters-heading">角色</h2><form className="entity-form" onSubmit={(event)=>submit(event,(data)=>run({kind:"character.create",character:createCharacterEntity(`character_${idFactory()}`,field(data,"displayName"),field(data,"color"),field(data,"portraitSlots").split(",").map((item)=>item.trim()).filter(Boolean),field(data,"defaultExpression"))}))}><input name="displayName" aria-label="角色显示名" required placeholder="显示名"/><input name="color" aria-label="角色颜色" required defaultValue="#8b7cff" pattern="#[0-9a-fA-F]{6}"/><input name="portraitSlots" aria-label="立绘槽位" required defaultValue="main"/><input name="defaultExpression" aria-label="默认表情" required defaultValue="neutral"/><button>新增角色</button></form><ol>{project.characters.characters.map((character,index)=><li key={String(character.id)}><form className="entity-row" onSubmit={(event)=>submit(event,(data)=>run({kind:"character.update",characterId:String(character.id),patch:createCharacterEntity(String(character.id),field(data,"displayName"),field(data,"color"),field(data,"portraitSlots").split(",").map((item)=>item.trim()).filter(Boolean),field(data,"defaultExpression"))}))}><input name="displayName" aria-label={`${String(character.displayName)}显示名`} defaultValue={String(character.displayName)}/><input name="color" aria-label={`${String(character.displayName)}颜色`} defaultValue={String(character.color)}/><input name="portraitSlots" aria-label={`${String(character.displayName)}立绘槽位`} defaultValue={Array.isArray(character.portraitSlots)?character.portraitSlots.join(","):"main"}/><input name="defaultExpression" aria-label={`${String(character.displayName)}默认表情`} defaultValue={String(character.defaultExpression)}/><button>保存角色</button><button type="button" aria-label={`${String(character.displayName)}上移`} disabled={index===0} onClick={()=>run({kind:"character.move",characterId:String(character.id),index:index-1})}>↑</button><button type="button" aria-label={`${String(character.displayName)}下移`} disabled={index===project.characters.characters.length-1} onClick={()=>run({kind:"character.move",characterId:String(character.id),index:index+1})}>↓</button><button type="button" aria-label={`删除角色${String(character.displayName)}`} onClick={()=>requestDelete("character",String(character.id))}>删除</button></form></li>)}</ol></section>
      <section className="entity-manager__card" aria-labelledby="variables-heading"><h2 id="variables-heading">变量</h2><form className="entity-form" onSubmit={(event)=>submit(event,(data)=>{const type=field(data,"type") as VariableType;const raw=field(data,"defaultValue");const value=type==="boolean"?raw==="true":type==="number"?Number(raw):raw;run({kind:"variable.create",variable:createVariableEntity(`variable_${idFactory()}`,field(data,"name"),type,value,field(data,"scope") as VariableScope)});} )}><input name="name" aria-label="变量名称" required placeholder="变量名称"/><select name="type" aria-label="变量类型"><option value="boolean">Boolean</option><option value="number">Number</option><option value="string">String</option></select><input name="defaultValue" aria-label="变量默认值" required defaultValue="false"/><select name="scope" aria-label="变量作用域"><option value="story">Story</option><option value="chapter">Chapter</option><option value="scene">Scene</option><option value="meta">Meta</option></select><button>新增变量</button></form><ol>{project.variables.variables.map((variable,index)=><li key={String(variable.id)}><form className="entity-row" onSubmit={(event)=>submit(event,(data)=>{const type=field(data,"type") as VariableType,raw=field(data,"defaultValue"),value=type==="boolean"?raw==="true":type==="number"?Number(raw):raw;run({kind:"variable.update",variableId:String(variable.id),patch:createVariableEntity(String(variable.id),field(data,"name"),type,value,field(data,"scope") as VariableScope)});} )}><input name="name" aria-label={`${String(variable.name)}变量名称`} defaultValue={String(variable.name)}/><select name="type" aria-label={`${String(variable.name)}变量类型`} defaultValue={String(variable.type)}><option value="boolean">Boolean</option><option value="number">Number</option><option value="string">String</option></select><input name="defaultValue" aria-label={`${String(variable.name)}变量默认值`} defaultValue={String(variable.defaultValue)}/><select name="scope" aria-label={`${String(variable.name)}变量作用域`} defaultValue={String(variable.scope)}><option value="story">Story</option><option value="chapter">Chapter</option><option value="scene">Scene</option><option value="meta">Meta</option></select><button>保存变量</button><button type="button" aria-label={`${String(variable.name)}上移`} disabled={index===0} onClick={()=>run({kind:"variable.move",variableId:String(variable.id),index:index-1})}>↑</button><button type="button" aria-label={`${String(variable.name)}下移`} disabled={index===project.variables.variables.length-1} onClick={()=>run({kind:"variable.move",variableId:String(variable.id),index:index+1})}>↓</button><button type="button" aria-label={`删除变量${String(variable.name)}`} onClick={()=>requestDelete("variable",String(variable.id))}>删除</button></form></li>)}</ol></section>
    </div>
    {pendingDelete?<section role="alertdialog" aria-labelledby="delete-analysis-title" className="project-conflict"><h2 id="delete-analysis-title">删除前引用分析</h2><p><code>{pendingDelete.id}</code> 有 {pendingDelete.references.length} 处引用，不能直接删除。</p><ul>{pendingDelete.references.map((item)=><li key={item.path}><code>{item.path}</code></li>)}</ul>{pendingDelete.kind!=="chapter"?<label>替代实体<select aria-label="替代实体" value={replacement} onChange={(event)=>setReplacement(event.target.value)}><option value="">请选择</option>{(pendingDelete.kind==="scene"?project.scenes:pendingDelete.kind==="character"?project.characters.characters:project.variables.variables).filter((item)=>item.id!==pendingDelete.id).map((item)=><option key={String(item.id)} value={String(item.id)}>{String("title" in item?item.title:"displayName" in item?item.displayName:item.name)}</option>)}</select></label>:null}<div className="project-home__actions"><button disabled={replacement===""} onClick={confirmDelete}>迁移引用并删除</button><button onClick={()=>setPendingDelete(null)}>取消</button></div></section>:null}
  </main>;
}
