import { describe,expect,it } from "vitest";
import { createSequenceInsertPlan,duplicateSequencePlan,sequenceMoveAfterId,sequenceRangeSelection,type SequenceInsertKind } from "./sequence-editor-model";
const refs={characterIds:["char_a"],sceneIds:["scene_a","scene_b"],labelIds:["label_a"],variableIds:["flag"],assetIds:["asset_bg"]};let serial=0;const id=(prefix:string)=>`${prefix}_${serial++}`;
describe("N21 sequence editor model",()=>{
  it("creates stable-ID plans for every P0 card",()=>{const kinds:SequenceInsertKind[]=["dialogue","narration","choice","label","jump","call","return","set","condition","wait","end","background","show","audio"];for(const kind of kinds){serial=0;const plan=createSequenceInsertPlan(kind,"scene_a",refs,id);expect(plan.length).toBeGreaterThan(0);expect(plan[0]?.afterId).toBe("scene_a");expect(plan.map((step)=>step.node.kind)).toContain(kind==="background"||kind==="show"||kind==="audio"?"directive":kind);}});
  it("creates two editable options for a new choice",()=>{serial=0;const plan=createSequenceInsertPlan("choice","stmt_a",refs,id);expect(plan.map((item)=>item.node.kind)).toEqual(["choice","choice-option","choice-option"]);expect(plan[1]?.afterId).toBe("stmt_0");});
  it("duplicates complex statements without reusing stable IDs",()=>{serial=0;const plan=duplicateSequencePlan({kind:"choice",id:"old",prompt:"Pick",options:[{id:"old_opt",label:"A",targetSceneId:"scene_b"}]},"anchor",id);expect(plan).toHaveLength(2);expect(plan[0]?.node).toMatchObject({kind:"choice",id:"stmt_0"});expect(plan[1]?.node).toMatchObject({kind:"choice-option",id:"option_2"});});
  it("supports bounded range selection and keyboard/touch move anchors",()=>{const statements=[{kind:"label",id:"a",name:"a"},{kind:"wait",id:"b",duration:"1s"},{kind:"end",id:"c",endingName:"end"}] as const;expect(sequenceRangeSelection(statements,"a","b")).toEqual(["a","b"]);expect(sequenceRangeSelection(statements,"a","c",2)).toEqual([]);expect(sequenceMoveAfterId(statements,"scene","b",-1)).toBe("scene");expect(sequenceMoveAfterId(statements,"scene","a",1)).toBe("b");expect(sequenceMoveAfterId(statements,"scene","b",1)).toBeUndefined();});
});
